// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/cloudstorage.proto

package model // import "github.com/TheTerribleChild/cloud_appplication_portal/cloud_applications/cloud_storage/internal/model"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AgentMessageType int32

const (
	AgentMessageType_NoMessage     AgentMessageType = 0
	AgentMessageType_ListDirectory AgentMessageType = 1
	AgentMessageType_UploadFile    AgentMessageType = 2
	AgentMessageType_DownloadFile  AgentMessageType = 3
)

var AgentMessageType_name = map[int32]string{
	0: "NoMessage",
	1: "ListDirectory",
	2: "UploadFile",
	3: "DownloadFile",
}
var AgentMessageType_value = map[string]int32{
	"NoMessage":     0,
	"ListDirectory": 1,
	"UploadFile":    2,
	"DownloadFile":  3,
}

func (x AgentMessageType) String() string {
	return proto.EnumName(AgentMessageType_name, int32(x))
}
func (AgentMessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cloudstorage_ef771b88ebd0eaec, []int{0}
}

type FileChunkRequest struct {
	MessageId            string         `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Info                 *FileChunkInfo `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *FileChunkRequest) Reset()         { *m = FileChunkRequest{} }
func (m *FileChunkRequest) String() string { return proto.CompactTextString(m) }
func (*FileChunkRequest) ProtoMessage()    {}
func (*FileChunkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cloudstorage_ef771b88ebd0eaec, []int{0}
}
func (m *FileChunkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileChunkRequest.Unmarshal(m, b)
}
func (m *FileChunkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileChunkRequest.Marshal(b, m, deterministic)
}
func (dst *FileChunkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileChunkRequest.Merge(dst, src)
}
func (m *FileChunkRequest) XXX_Size() int {
	return xxx_messageInfo_FileChunkRequest.Size(m)
}
func (m *FileChunkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FileChunkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FileChunkRequest proto.InternalMessageInfo

func (m *FileChunkRequest) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func (m *FileChunkRequest) GetInfo() *FileChunkInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type FileChunk struct {
	MessageId            string         `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Info                 *FileChunkInfo `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	Content              []byte         `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *FileChunk) Reset()         { *m = FileChunk{} }
func (m *FileChunk) String() string { return proto.CompactTextString(m) }
func (*FileChunk) ProtoMessage()    {}
func (*FileChunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_cloudstorage_ef771b88ebd0eaec, []int{1}
}
func (m *FileChunk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileChunk.Unmarshal(m, b)
}
func (m *FileChunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileChunk.Marshal(b, m, deterministic)
}
func (dst *FileChunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileChunk.Merge(dst, src)
}
func (m *FileChunk) XXX_Size() int {
	return xxx_messageInfo_FileChunk.Size(m)
}
func (m *FileChunk) XXX_DiscardUnknown() {
	xxx_messageInfo_FileChunk.DiscardUnknown(m)
}

var xxx_messageInfo_FileChunk proto.InternalMessageInfo

func (m *FileChunk) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func (m *FileChunk) GetInfo() *FileChunkInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *FileChunk) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type FileChunkInfo struct {
	Offset               int64    `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Size                 int64    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileChunkInfo) Reset()         { *m = FileChunkInfo{} }
func (m *FileChunkInfo) String() string { return proto.CompactTextString(m) }
func (*FileChunkInfo) ProtoMessage()    {}
func (*FileChunkInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_cloudstorage_ef771b88ebd0eaec, []int{2}
}
func (m *FileChunkInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileChunkInfo.Unmarshal(m, b)
}
func (m *FileChunkInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileChunkInfo.Marshal(b, m, deterministic)
}
func (dst *FileChunkInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileChunkInfo.Merge(dst, src)
}
func (m *FileChunkInfo) XXX_Size() int {
	return xxx_messageInfo_FileChunkInfo.Size(m)
}
func (m *FileChunkInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FileChunkInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FileChunkInfo proto.InternalMessageInfo

func (m *FileChunkInfo) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *FileChunkInfo) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type RegisterAgentRequest struct {
	Host                 string   `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterAgentRequest) Reset()         { *m = RegisterAgentRequest{} }
func (m *RegisterAgentRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterAgentRequest) ProtoMessage()    {}
func (*RegisterAgentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cloudstorage_ef771b88ebd0eaec, []int{3}
}
func (m *RegisterAgentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterAgentRequest.Unmarshal(m, b)
}
func (m *RegisterAgentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterAgentRequest.Marshal(b, m, deterministic)
}
func (dst *RegisterAgentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterAgentRequest.Merge(dst, src)
}
func (m *RegisterAgentRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterAgentRequest.Size(m)
}
func (m *RegisterAgentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterAgentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterAgentRequest proto.InternalMessageInfo

func (m *RegisterAgentRequest) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *RegisterAgentRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type RegisterAgentResponse struct {
	AgentId              string   `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterAgentResponse) Reset()         { *m = RegisterAgentResponse{} }
func (m *RegisterAgentResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterAgentResponse) ProtoMessage()    {}
func (*RegisterAgentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cloudstorage_ef771b88ebd0eaec, []int{4}
}
func (m *RegisterAgentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterAgentResponse.Unmarshal(m, b)
}
func (m *RegisterAgentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterAgentResponse.Marshal(b, m, deterministic)
}
func (dst *RegisterAgentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterAgentResponse.Merge(dst, src)
}
func (m *RegisterAgentResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterAgentResponse.Size(m)
}
func (m *RegisterAgentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterAgentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterAgentResponse proto.InternalMessageInfo

func (m *RegisterAgentResponse) GetAgentId() string {
	if m != nil {
		return m.AgentId
	}
	return ""
}

type AgentPollRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	AgentId              string   `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgentPollRequest) Reset()         { *m = AgentPollRequest{} }
func (m *AgentPollRequest) String() string { return proto.CompactTextString(m) }
func (*AgentPollRequest) ProtoMessage()    {}
func (*AgentPollRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cloudstorage_ef771b88ebd0eaec, []int{5}
}
func (m *AgentPollRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentPollRequest.Unmarshal(m, b)
}
func (m *AgentPollRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentPollRequest.Marshal(b, m, deterministic)
}
func (dst *AgentPollRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentPollRequest.Merge(dst, src)
}
func (m *AgentPollRequest) XXX_Size() int {
	return xxx_messageInfo_AgentPollRequest.Size(m)
}
func (m *AgentPollRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentPollRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AgentPollRequest proto.InternalMessageInfo

func (m *AgentPollRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *AgentPollRequest) GetAgentId() string {
	if m != nil {
		return m.AgentId
	}
	return ""
}

type AgentInfo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version              string   `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgentInfo) Reset()         { *m = AgentInfo{} }
func (m *AgentInfo) String() string { return proto.CompactTextString(m) }
func (*AgentInfo) ProtoMessage()    {}
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_cloudstorage_ef771b88ebd0eaec, []int{6}
}
func (m *AgentInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentInfo.Unmarshal(m, b)
}
func (m *AgentInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentInfo.Marshal(b, m, deterministic)
}
func (dst *AgentInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentInfo.Merge(dst, src)
}
func (m *AgentInfo) XXX_Size() int {
	return xxx_messageInfo_AgentInfo.Size(m)
}
func (m *AgentInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AgentInfo proto.InternalMessageInfo

func (m *AgentInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AgentInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AgentInfo) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type AgentMessage struct {
	MessageId            string           `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Type                 AgentMessageType `protobuf:"varint,2,opt,name=type,proto3,enum=cloudstorage.AgentMessageType" json:"type,omitempty"`
	Token                string           `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Content              []byte           `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AgentMessage) Reset()         { *m = AgentMessage{} }
func (m *AgentMessage) String() string { return proto.CompactTextString(m) }
func (*AgentMessage) ProtoMessage()    {}
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_cloudstorage_ef771b88ebd0eaec, []int{7}
}
func (m *AgentMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentMessage.Unmarshal(m, b)
}
func (m *AgentMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentMessage.Marshal(b, m, deterministic)
}
func (dst *AgentMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentMessage.Merge(dst, src)
}
func (m *AgentMessage) XXX_Size() int {
	return xxx_messageInfo_AgentMessage.Size(m)
}
func (m *AgentMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentMessage.DiscardUnknown(m)
}

var xxx_messageInfo_AgentMessage proto.InternalMessageInfo

func (m *AgentMessage) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func (m *AgentMessage) GetType() AgentMessageType {
	if m != nil {
		return m.Type
	}
	return AgentMessageType_NoMessage
}

func (m *AgentMessage) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *AgentMessage) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type ListDirectoryMessageContent struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListDirectoryMessageContent) Reset()         { *m = ListDirectoryMessageContent{} }
func (m *ListDirectoryMessageContent) String() string { return proto.CompactTextString(m) }
func (*ListDirectoryMessageContent) ProtoMessage()    {}
func (*ListDirectoryMessageContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_cloudstorage_ef771b88ebd0eaec, []int{8}
}
func (m *ListDirectoryMessageContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDirectoryMessageContent.Unmarshal(m, b)
}
func (m *ListDirectoryMessageContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDirectoryMessageContent.Marshal(b, m, deterministic)
}
func (dst *ListDirectoryMessageContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDirectoryMessageContent.Merge(dst, src)
}
func (m *ListDirectoryMessageContent) XXX_Size() int {
	return xxx_messageInfo_ListDirectoryMessageContent.Size(m)
}
func (m *ListDirectoryMessageContent) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDirectoryMessageContent.DiscardUnknown(m)
}

var xxx_messageInfo_ListDirectoryMessageContent proto.InternalMessageInfo

func (m *ListDirectoryMessageContent) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type FileUploadDownloadMessageContent struct {
	RemoteUrl            string   `protobuf:"bytes,1,opt,name=remote_url,json=remoteUrl,proto3" json:"remote_url,omitempty"`
	Path                 []string `protobuf:"bytes,2,rep,name=path,proto3" json:"path,omitempty"`
	MaxSize              int64    `protobuf:"varint,3,opt,name=max_size,json=maxSize,proto3" json:"max_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileUploadDownloadMessageContent) Reset()         { *m = FileUploadDownloadMessageContent{} }
func (m *FileUploadDownloadMessageContent) String() string { return proto.CompactTextString(m) }
func (*FileUploadDownloadMessageContent) ProtoMessage()    {}
func (*FileUploadDownloadMessageContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_cloudstorage_ef771b88ebd0eaec, []int{9}
}
func (m *FileUploadDownloadMessageContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileUploadDownloadMessageContent.Unmarshal(m, b)
}
func (m *FileUploadDownloadMessageContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileUploadDownloadMessageContent.Marshal(b, m, deterministic)
}
func (dst *FileUploadDownloadMessageContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileUploadDownloadMessageContent.Merge(dst, src)
}
func (m *FileUploadDownloadMessageContent) XXX_Size() int {
	return xxx_messageInfo_FileUploadDownloadMessageContent.Size(m)
}
func (m *FileUploadDownloadMessageContent) XXX_DiscardUnknown() {
	xxx_messageInfo_FileUploadDownloadMessageContent.DiscardUnknown(m)
}

var xxx_messageInfo_FileUploadDownloadMessageContent proto.InternalMessageInfo

func (m *FileUploadDownloadMessageContent) GetRemoteUrl() string {
	if m != nil {
		return m.RemoteUrl
	}
	return ""
}

func (m *FileUploadDownloadMessageContent) GetPath() []string {
	if m != nil {
		return m.Path
	}
	return nil
}

func (m *FileUploadDownloadMessageContent) GetMaxSize() int64 {
	if m != nil {
		return m.MaxSize
	}
	return 0
}

type DirectoryContent struct {
	MessageId            string      `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Path                 string      `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Items                []*FileItem `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	ErrorMsg             string      `protobuf:"bytes,4,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *DirectoryContent) Reset()         { *m = DirectoryContent{} }
func (m *DirectoryContent) String() string { return proto.CompactTextString(m) }
func (*DirectoryContent) ProtoMessage()    {}
func (*DirectoryContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_cloudstorage_ef771b88ebd0eaec, []int{10}
}
func (m *DirectoryContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DirectoryContent.Unmarshal(m, b)
}
func (m *DirectoryContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DirectoryContent.Marshal(b, m, deterministic)
}
func (dst *DirectoryContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DirectoryContent.Merge(dst, src)
}
func (m *DirectoryContent) XXX_Size() int {
	return xxx_messageInfo_DirectoryContent.Size(m)
}
func (m *DirectoryContent) XXX_DiscardUnknown() {
	xxx_messageInfo_DirectoryContent.DiscardUnknown(m)
}

var xxx_messageInfo_DirectoryContent proto.InternalMessageInfo

func (m *DirectoryContent) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func (m *DirectoryContent) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *DirectoryContent) GetItems() []*FileItem {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *DirectoryContent) GetErrorMsg() string {
	if m != nil {
		return m.ErrorMsg
	}
	return ""
}

type AgentError struct {
	MessageId            string   `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ErrorMsg             string   `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgentError) Reset()         { *m = AgentError{} }
func (m *AgentError) String() string { return proto.CompactTextString(m) }
func (*AgentError) ProtoMessage()    {}
func (*AgentError) Descriptor() ([]byte, []int) {
	return fileDescriptor_cloudstorage_ef771b88ebd0eaec, []int{11}
}
func (m *AgentError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentError.Unmarshal(m, b)
}
func (m *AgentError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentError.Marshal(b, m, deterministic)
}
func (dst *AgentError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentError.Merge(dst, src)
}
func (m *AgentError) XXX_Size() int {
	return xxx_messageInfo_AgentError.Size(m)
}
func (m *AgentError) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentError.DiscardUnknown(m)
}

var xxx_messageInfo_AgentError proto.InternalMessageInfo

func (m *AgentError) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func (m *AgentError) GetErrorMsg() string {
	if m != nil {
		return m.ErrorMsg
	}
	return ""
}

type Progress struct {
	Current              int64    `protobuf:"varint,1,opt,name=current,proto3" json:"current,omitempty"`
	Total                int64    `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Progress) Reset()         { *m = Progress{} }
func (m *Progress) String() string { return proto.CompactTextString(m) }
func (*Progress) ProtoMessage()    {}
func (*Progress) Descriptor() ([]byte, []int) {
	return fileDescriptor_cloudstorage_ef771b88ebd0eaec, []int{12}
}
func (m *Progress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Progress.Unmarshal(m, b)
}
func (m *Progress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Progress.Marshal(b, m, deterministic)
}
func (dst *Progress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Progress.Merge(dst, src)
}
func (m *Progress) XXX_Size() int {
	return xxx_messageInfo_Progress.Size(m)
}
func (m *Progress) XXX_DiscardUnknown() {
	xxx_messageInfo_Progress.DiscardUnknown(m)
}

var xxx_messageInfo_Progress proto.InternalMessageInfo

func (m *Progress) GetCurrent() int64 {
	if m != nil {
		return m.Current
	}
	return 0
}

func (m *Progress) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_cloudstorage_ef771b88ebd0eaec, []int{13}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type FileItem struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Size                 int64    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	IsDirectory          bool     `protobuf:"varint,3,opt,name=is_directory,json=isDirectory,proto3" json:"is_directory,omitempty"`
	CanRead              bool     `protobuf:"varint,4,opt,name=can_read,json=canRead,proto3" json:"can_read,omitempty"`
	CanWrite             bool     `protobuf:"varint,5,opt,name=can_write,json=canWrite,proto3" json:"can_write,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileItem) Reset()         { *m = FileItem{} }
func (m *FileItem) String() string { return proto.CompactTextString(m) }
func (*FileItem) ProtoMessage()    {}
func (*FileItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_cloudstorage_ef771b88ebd0eaec, []int{14}
}
func (m *FileItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileItem.Unmarshal(m, b)
}
func (m *FileItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileItem.Marshal(b, m, deterministic)
}
func (dst *FileItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileItem.Merge(dst, src)
}
func (m *FileItem) XXX_Size() int {
	return xxx_messageInfo_FileItem.Size(m)
}
func (m *FileItem) XXX_DiscardUnknown() {
	xxx_messageInfo_FileItem.DiscardUnknown(m)
}

var xxx_messageInfo_FileItem proto.InternalMessageInfo

func (m *FileItem) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *FileItem) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *FileItem) GetIsDirectory() bool {
	if m != nil {
		return m.IsDirectory
	}
	return false
}

func (m *FileItem) GetCanRead() bool {
	if m != nil {
		return m.CanRead
	}
	return false
}

func (m *FileItem) GetCanWrite() bool {
	if m != nil {
		return m.CanWrite
	}
	return false
}

func init() {
	proto.RegisterType((*FileChunkRequest)(nil), "cloudstorage.FileChunkRequest")
	proto.RegisterType((*FileChunk)(nil), "cloudstorage.FileChunk")
	proto.RegisterType((*FileChunkInfo)(nil), "cloudstorage.FileChunkInfo")
	proto.RegisterType((*RegisterAgentRequest)(nil), "cloudstorage.RegisterAgentRequest")
	proto.RegisterType((*RegisterAgentResponse)(nil), "cloudstorage.RegisterAgentResponse")
	proto.RegisterType((*AgentPollRequest)(nil), "cloudstorage.AgentPollRequest")
	proto.RegisterType((*AgentInfo)(nil), "cloudstorage.AgentInfo")
	proto.RegisterType((*AgentMessage)(nil), "cloudstorage.AgentMessage")
	proto.RegisterType((*ListDirectoryMessageContent)(nil), "cloudstorage.ListDirectoryMessageContent")
	proto.RegisterType((*FileUploadDownloadMessageContent)(nil), "cloudstorage.FileUploadDownloadMessageContent")
	proto.RegisterType((*DirectoryContent)(nil), "cloudstorage.DirectoryContent")
	proto.RegisterType((*AgentError)(nil), "cloudstorage.AgentError")
	proto.RegisterType((*Progress)(nil), "cloudstorage.Progress")
	proto.RegisterType((*Empty)(nil), "cloudstorage.Empty")
	proto.RegisterType((*FileItem)(nil), "cloudstorage.FileItem")
	proto.RegisterEnum("cloudstorage.AgentMessageType", AgentMessageType_name, AgentMessageType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StorageServiceClient is the client API for StorageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StorageServiceClient interface {
	UploadFile(ctx context.Context, in *FileChunk, opts ...grpc.CallOption) (*FileChunkRequest, error)
	DownloadFile(ctx context.Context, in *FileChunkRequest, opts ...grpc.CallOption) (*FileChunk, error)
}

type storageServiceClient struct {
	cc *grpc.ClientConn
}

func NewStorageServiceClient(cc *grpc.ClientConn) StorageServiceClient {
	return &storageServiceClient{cc}
}

func (c *storageServiceClient) UploadFile(ctx context.Context, in *FileChunk, opts ...grpc.CallOption) (*FileChunkRequest, error) {
	out := new(FileChunkRequest)
	err := c.cc.Invoke(ctx, "/cloudstorage.StorageService/UploadFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) DownloadFile(ctx context.Context, in *FileChunkRequest, opts ...grpc.CallOption) (*FileChunk, error) {
	out := new(FileChunk)
	err := c.cc.Invoke(ctx, "/cloudstorage.StorageService/DownloadFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageServiceServer is the server API for StorageService service.
type StorageServiceServer interface {
	UploadFile(context.Context, *FileChunk) (*FileChunkRequest, error)
	DownloadFile(context.Context, *FileChunkRequest) (*FileChunk, error)
}

func RegisterStorageServiceServer(s *grpc.Server, srv StorageServiceServer) {
	s.RegisterService(&_StorageService_serviceDesc, srv)
}

func _StorageService_UploadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileChunk)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).UploadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloudstorage.StorageService/UploadFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).UploadFile(ctx, req.(*FileChunk))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_DownloadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).DownloadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloudstorage.StorageService/DownloadFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).DownloadFile(ctx, req.(*FileChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StorageService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cloudstorage.StorageService",
	HandlerType: (*StorageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadFile",
			Handler:    _StorageService_UploadFile_Handler,
		},
		{
			MethodName: "DownloadFile",
			Handler:    _StorageService_DownloadFile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/cloudstorage.proto",
}

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AgentServiceClient interface {
	RegisterAgent(ctx context.Context, in *RegisterAgentRequest, opts ...grpc.CallOption) (*RegisterAgentResponse, error)
	Poll(ctx context.Context, in *AgentPollRequest, opts ...grpc.CallOption) (*AgentMessage, error)
	PublishDirectoryContent(ctx context.Context, in *DirectoryContent, opts ...grpc.CallOption) (*Empty, error)
	PublishUploadDownloadProgress(ctx context.Context, in *Progress, opts ...grpc.CallOption) (*Empty, error)
	PublishError(ctx context.Context, in *AgentError, opts ...grpc.CallOption) (*Empty, error)
}

type agentServiceClient struct {
	cc *grpc.ClientConn
}

func NewAgentServiceClient(cc *grpc.ClientConn) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) RegisterAgent(ctx context.Context, in *RegisterAgentRequest, opts ...grpc.CallOption) (*RegisterAgentResponse, error) {
	out := new(RegisterAgentResponse)
	err := c.cc.Invoke(ctx, "/cloudstorage.AgentService/RegisterAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) Poll(ctx context.Context, in *AgentPollRequest, opts ...grpc.CallOption) (*AgentMessage, error) {
	out := new(AgentMessage)
	err := c.cc.Invoke(ctx, "/cloudstorage.AgentService/Poll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) PublishDirectoryContent(ctx context.Context, in *DirectoryContent, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/cloudstorage.AgentService/PublishDirectoryContent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) PublishUploadDownloadProgress(ctx context.Context, in *Progress, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/cloudstorage.AgentService/PublishUploadDownloadProgress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) PublishError(ctx context.Context, in *AgentError, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/cloudstorage.AgentService/PublishError", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
type AgentServiceServer interface {
	RegisterAgent(context.Context, *RegisterAgentRequest) (*RegisterAgentResponse, error)
	Poll(context.Context, *AgentPollRequest) (*AgentMessage, error)
	PublishDirectoryContent(context.Context, *DirectoryContent) (*Empty, error)
	PublishUploadDownloadProgress(context.Context, *Progress) (*Empty, error)
	PublishError(context.Context, *AgentError) (*Empty, error)
}

func RegisterAgentServiceServer(s *grpc.Server, srv AgentServiceServer) {
	s.RegisterService(&_AgentService_serviceDesc, srv)
}

func _AgentService_RegisterAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).RegisterAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloudstorage.AgentService/RegisterAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).RegisterAgent(ctx, req.(*RegisterAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_Poll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentPollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Poll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloudstorage.AgentService/Poll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Poll(ctx, req.(*AgentPollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_PublishDirectoryContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DirectoryContent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).PublishDirectoryContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloudstorage.AgentService/PublishDirectoryContent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).PublishDirectoryContent(ctx, req.(*DirectoryContent))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_PublishUploadDownloadProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Progress)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).PublishUploadDownloadProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloudstorage.AgentService/PublishUploadDownloadProgress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).PublishUploadDownloadProgress(ctx, req.(*Progress))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_PublishError_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentError)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).PublishError(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloudstorage.AgentService/PublishError",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).PublishError(ctx, req.(*AgentError))
	}
	return interceptor(ctx, in, info, handler)
}

var _AgentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cloudstorage.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterAgent",
			Handler:    _AgentService_RegisterAgent_Handler,
		},
		{
			MethodName: "Poll",
			Handler:    _AgentService_Poll_Handler,
		},
		{
			MethodName: "PublishDirectoryContent",
			Handler:    _AgentService_PublishDirectoryContent_Handler,
		},
		{
			MethodName: "PublishUploadDownloadProgress",
			Handler:    _AgentService_PublishUploadDownloadProgress_Handler,
		},
		{
			MethodName: "PublishError",
			Handler:    _AgentService_PublishError_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/cloudstorage.proto",
}

func init() {
	proto.RegisterFile("proto/cloudstorage.proto", fileDescriptor_cloudstorage_ef771b88ebd0eaec)
}

var fileDescriptor_cloudstorage_ef771b88ebd0eaec = []byte{
	// 845 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0x8e, 0xe3, 0x74, 0x93, 0x9c, 0xa6, 0x55, 0x18, 0x96, 0xdd, 0x90, 0xaa, 0xab, 0x60, 0x6e,
	0x2a, 0x84, 0x1a, 0x11, 0xee, 0xe0, 0x02, 0x41, 0xbb, 0x40, 0x24, 0x76, 0x55, 0xb9, 0x5d, 0x90,
	0xf6, 0xc6, 0x9a, 0xd8, 0xa7, 0xce, 0x68, 0xed, 0x19, 0x33, 0x33, 0xde, 0xdd, 0xf2, 0x0e, 0x48,
	0x20, 0x5e, 0x81, 0x07, 0x45, 0x33, 0xfe, 0x89, 0x9d, 0x4d, 0xda, 0x1b, 0xae, 0xea, 0xf3, 0x33,
	0xdf, 0xf9, 0xf9, 0xce, 0x39, 0x0d, 0x4c, 0x32, 0x29, 0xb4, 0x98, 0x87, 0x89, 0xc8, 0x23, 0xa5,
	0x85, 0xa4, 0x31, 0x9e, 0x5b, 0x15, 0x19, 0x35, 0x75, 0xde, 0x0a, 0xc6, 0x3f, 0xb2, 0x04, 0x2f,
	0xd6, 0x39, 0x7f, 0xe3, 0xe3, 0xef, 0x39, 0x2a, 0x4d, 0x4e, 0x01, 0x52, 0x54, 0x8a, 0xc6, 0x18,
	0xb0, 0x68, 0xe2, 0xcc, 0x9c, 0xb3, 0xa1, 0x3f, 0x2c, 0x35, 0xcb, 0x88, 0xcc, 0xa1, 0xc7, 0xf8,
	0xad, 0x98, 0x74, 0x67, 0xce, 0xd9, 0xe1, 0xe2, 0xe4, 0xbc, 0x15, 0xa3, 0x06, 0x5b, 0xf2, 0x5b,
	0xe1, 0x5b, 0x47, 0x2f, 0x87, 0x61, 0xad, 0xfe, 0xbf, 0xc1, 0xc9, 0x04, 0xfa, 0xa1, 0xe0, 0x1a,
	0xb9, 0x9e, 0xb8, 0x33, 0xe7, 0x6c, 0xe4, 0x57, 0xa2, 0xf7, 0x2d, 0x1c, 0xb5, 0x1e, 0x90, 0x27,
	0xf0, 0x48, 0xdc, 0xde, 0x2a, 0xd4, 0x36, 0xac, 0xeb, 0x97, 0x12, 0x21, 0xd0, 0x53, 0xec, 0x0f,
	0xb4, 0x31, 0x5d, 0xdf, 0x7e, 0x7b, 0x97, 0xf0, 0xd8, 0xc7, 0x98, 0x29, 0x8d, 0xf2, 0xfb, 0x18,
	0xb9, 0xae, 0x7a, 0x43, 0xa0, 0xb7, 0x16, 0x4a, 0x97, 0x89, 0xdb, 0x6f, 0x93, 0xc2, 0x5b, 0x94,
	0x8a, 0x09, 0x6e, 0x21, 0x86, 0x7e, 0x25, 0x7a, 0x0b, 0xf8, 0x64, 0x0b, 0x45, 0x65, 0x82, 0x2b,
	0x24, 0x9f, 0xc2, 0x80, 0x1a, 0xc5, 0xa6, 0x07, 0x7d, 0x2b, 0x2f, 0x23, 0xef, 0x02, 0xc6, 0xd6,
	0xf7, 0x4a, 0x24, 0x49, 0x15, 0xf5, 0x31, 0x1c, 0x68, 0xf1, 0x06, 0x79, 0xe9, 0x5b, 0x08, 0x2d,
	0x90, 0x6e, 0x1b, 0x64, 0x09, 0x43, 0x0b, 0x62, 0xeb, 0x3e, 0x86, 0x6e, 0x1d, 0xa6, 0xcb, 0x22,
	0x53, 0x03, 0xa7, 0x29, 0x96, 0x6f, 0xec, 0x77, 0xb3, 0x06, 0xb7, 0x5d, 0xc3, 0xdf, 0x0e, 0x8c,
	0x2c, 0xd6, 0x8b, 0x82, 0xa4, 0x87, 0x18, 0x5c, 0x40, 0x4f, 0xdf, 0x65, 0x05, 0xfa, 0xf1, 0xe2,
	0x59, 0x9b, 0xc1, 0x26, 0xd0, 0xcd, 0x5d, 0x86, 0xbe, 0xf5, 0xdd, 0xd4, 0xe7, 0x36, 0xeb, 0x6b,
	0x50, 0xdb, 0x6b, 0x53, 0xfb, 0x15, 0x9c, 0xfc, 0xc2, 0x94, 0xbe, 0x64, 0x12, 0x43, 0x2d, 0xe4,
	0x5d, 0x89, 0x78, 0x51, 0x98, 0x4d, 0x81, 0x19, 0xd5, 0xeb, 0x8a, 0x24, 0xf3, 0xed, 0x65, 0x30,
	0x33, 0xd3, 0xf0, 0x2a, 0x4b, 0x04, 0x8d, 0x2e, 0xc5, 0x3b, 0x6e, 0xfe, 0x6e, 0xbd, 0x3b, 0x05,
	0x90, 0x98, 0x0a, 0x8d, 0x41, 0x2e, 0x93, 0xaa, 0xb2, 0x42, 0xf3, 0x4a, 0x26, 0x35, 0x6c, 0x77,
	0xe6, 0x56, 0xb0, 0x86, 0x83, 0x94, 0xbe, 0x0f, 0xec, 0xfc, 0xb8, 0x76, 0x7e, 0xfa, 0x29, 0x7d,
	0x7f, 0x6d, 0x46, 0xe8, 0x2f, 0x07, 0xc6, 0x75, 0x86, 0x8d, 0x10, 0xf7, 0x35, 0x6f, 0x13, 0xa2,
	0xce, 0x9c, 0x7c, 0x09, 0x07, 0x4c, 0x63, 0xaa, 0x26, 0xee, 0xcc, 0x3d, 0x3b, 0x5c, 0x3c, 0xf9,
	0x70, 0x27, 0x96, 0x1a, 0x53, 0xbf, 0x70, 0x22, 0x27, 0x30, 0x44, 0x29, 0x85, 0x0c, 0x52, 0x15,
	0xdb, 0xb6, 0x0d, 0xfd, 0x81, 0x55, 0xbc, 0x50, 0xb1, 0xf7, 0x33, 0x80, 0x65, 0xe0, 0xb9, 0x51,
	0x3c, 0x94, 0x4b, 0x0b, 0xa9, 0xbb, 0x85, 0xf4, 0x0d, 0x0c, 0xae, 0xa4, 0x88, 0x25, 0x2a, 0x65,
	0x79, 0xca, 0xa5, 0x34, 0x3c, 0x15, 0x8b, 0x55, 0x89, 0x05, 0xaf, 0x9a, 0x26, 0xe5, 0x6a, 0x15,
	0x82, 0xd7, 0x87, 0x83, 0xe7, 0x69, 0xa6, 0xef, 0xbc, 0x3f, 0x1d, 0x18, 0x54, 0xf9, 0xef, 0x22,
	0x6d, 0xd7, 0x66, 0x92, 0xcf, 0x60, 0xc4, 0x54, 0x10, 0x55, 0x8d, 0xb5, 0x5d, 0x1f, 0xf8, 0x87,
	0x4c, 0xd5, 0xbd, 0x36, 0xa4, 0x84, 0x94, 0x07, 0x12, 0x69, 0x64, 0x5b, 0x30, 0xf0, 0xfb, 0x21,
	0xe5, 0x3e, 0x52, 0x5b, 0x94, 0x31, 0xbd, 0x93, 0x4c, 0xe3, 0xe4, 0xc0, 0xda, 0x8c, 0xef, 0x6f,
	0x46, 0xfe, 0xe2, 0xd7, 0x72, 0xf5, 0x1a, 0x03, 0x4a, 0x8e, 0x60, 0xf8, 0x52, 0x94, 0x8a, 0x71,
	0x87, 0x7c, 0x04, 0x47, 0xad, 0xc9, 0x1b, 0x3b, 0xe4, 0x18, 0xa0, 0x98, 0x2a, 0x53, 0xca, 0xb8,
	0x4b, 0xc6, 0x30, 0xaa, 0xe6, 0xcb, 0x6a, 0xdc, 0xc5, 0xbf, 0x0e, 0x1c, 0x5f, 0x17, 0x7c, 0x5d,
	0xa3, 0x7c, 0xcb, 0x42, 0x24, 0x3f, 0x35, 0x1f, 0x91, 0xa7, 0x7b, 0xee, 0xdc, 0xf4, 0xd9, 0x1e,
	0x43, 0x79, 0x18, 0xbc, 0x0e, 0x59, 0xb6, 0xa3, 0x91, 0x07, 0x5e, 0x4c, 0xf7, 0x85, 0xf2, 0x3a,
	0x8b, 0x7f, 0xdc, 0x72, 0xd3, 0xab, 0x24, 0x5f, 0xc3, 0x51, 0xeb, 0x7c, 0x11, 0xaf, 0xfd, 0x78,
	0xd7, 0x85, 0x9c, 0x7e, 0x7e, 0xaf, 0x4f, 0x71, 0xff, 0xbc, 0x0e, 0xb9, 0x84, 0x9e, 0xb9, 0x70,
	0x64, 0xd7, 0x81, 0x68, 0x9c, 0xbe, 0xe9, 0x74, 0xff, 0x01, 0xf1, 0x3a, 0xe4, 0x0a, 0x9e, 0x5e,
	0xe5, 0xab, 0x84, 0xa9, 0xf5, 0x07, 0x9b, 0xb6, 0x05, 0xbc, 0x6d, 0x9f, 0x7e, 0xdc, 0xb6, 0x17,
	0x13, 0xd9, 0x21, 0x2f, 0xe1, 0xb4, 0x44, 0x6c, 0x9f, 0x8a, 0x7a, 0xda, 0xb7, 0xf6, 0xaf, 0xd2,
	0xef, 0xc3, 0xfb, 0x0e, 0x46, 0x25, 0x5e, 0xb1, 0x74, 0x93, 0x1d, 0xf5, 0x58, 0xcb, 0x1e, 0x80,
	0x1f, 0xe2, 0xd7, 0x18, 0x33, 0xbd, 0xce, 0x57, 0xe7, 0xa1, 0x48, 0xe7, 0x37, 0x6b, 0xbc, 0x41,
	0x29, 0xd9, 0xca, 0xd0, 0xc6, 0x92, 0xa8, 0xf8, 0x0f, 0x1f, 0xd0, 0x2c, 0xcb, 0x12, 0x16, 0x52,
	0xcd, 0x04, 0x0f, 0x32, 0x21, 0x35, 0x4d, 0x36, 0x96, 0xca, 0xa0, 0x4a, 0x55, 0x19, 0x61, 0xce,
	0xb8, 0x46, 0xc9, 0x69, 0x32, 0x4f, 0x45, 0x84, 0xc9, 0xea, 0x91, 0xfd, 0x7d, 0xf0, 0xf5, 0x7f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0xba, 0x6a, 0x03, 0x18, 0x3b, 0x08, 0x00, 0x00,
}
