// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model/model.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Account struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_312ac5bcab6cbb43, []int{0}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Account) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FirstName            string   `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	AccountId            string   `protobuf:"bytes,5,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	PasswordHash         string   `protobuf:"bytes,6,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	CreatedDate          int64    `protobuf:"varint,7,opt,name=created_date,json=createdDate,proto3" json:"created_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_312ac5bcab6cbb43, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *User) GetPasswordHash() string {
	if m != nil {
		return m.PasswordHash
	}
	return ""
}

func (m *User) GetCreatedDate() int64 {
	if m != nil {
		return m.CreatedDate
	}
	return 0
}

type Agent struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId            string   `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Agent) Reset()         { *m = Agent{} }
func (m *Agent) String() string { return proto.CompactTextString(m) }
func (*Agent) ProtoMessage()    {}
func (*Agent) Descriptor() ([]byte, []int) {
	return fileDescriptor_312ac5bcab6cbb43, []int{2}
}

func (m *Agent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Agent.Unmarshal(m, b)
}
func (m *Agent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Agent.Marshal(b, m, deterministic)
}
func (m *Agent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Agent.Merge(m, src)
}
func (m *Agent) XXX_Size() int {
	return xxx_messageInfo_Agent.Size(m)
}
func (m *Agent) XXX_DiscardUnknown() {
	xxx_messageInfo_Agent.DiscardUnknown(m)
}

var xxx_messageInfo_Agent proto.InternalMessageInfo

func (m *Agent) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Agent) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *Agent) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Account)(nil), "model.Account")
	proto.RegisterType((*User)(nil), "model.User")
	proto.RegisterType((*Agent)(nil), "model.Agent")
}

func init() {
	proto.RegisterFile("model/model.proto", fileDescriptor_312ac5bcab6cbb43)
}

var fileDescriptor_312ac5bcab6cbb43 = []byte{
	// 274 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x4f, 0x4b, 0xf4, 0x30,
	0x10, 0xc6, 0x69, 0x77, 0xbb, 0xfb, 0x76, 0xde, 0x55, 0x30, 0x78, 0x28, 0xc8, 0xc2, 0x5a, 0x41,
	0x7a, 0xd1, 0x1e, 0xfc, 0x04, 0x55, 0x0f, 0xea, 0xc1, 0xc3, 0x82, 0x17, 0x2f, 0x65, 0xb6, 0x19,
	0x6d, 0x20, 0x69, 0x4a, 0x92, 0xc5, 0x8f, 0xe9, 0x57, 0x12, 0xa7, 0x2d, 0xe2, 0x9f, 0x4b, 0xc8,
	0xfc, 0x9e, 0x27, 0x99, 0x64, 0x1e, 0x38, 0x32, 0x56, 0x92, 0x2e, 0x79, 0xbd, 0xec, 0x9d, 0x0d,
	0x56, 0x24, 0x5c, 0xe4, 0x17, 0xb0, 0xac, 0x9a, 0xc6, 0xee, 0xbb, 0x20, 0x0e, 0x21, 0x56, 0x32,
	0x8b, 0x36, 0x51, 0x91, 0x6e, 0x63, 0x25, 0x85, 0x80, 0x79, 0x87, 0x86, 0xb2, 0x98, 0x09, 0xef,
	0xf3, 0xf7, 0x08, 0xe6, 0x4f, 0x9e, 0xdc, 0x2f, 0xf3, 0x31, 0x24, 0x64, 0x50, 0xe9, 0xd1, 0x3d,
	0x14, 0x62, 0x0d, 0xf0, 0xa2, 0x9c, 0x0f, 0x35, 0x5f, 0x34, 0x63, 0x29, 0x65, 0xf2, 0x88, 0x86,
	0xc4, 0x09, 0xa4, 0x1a, 0x27, 0x75, 0xce, 0xea, 0xbf, 0x4f, 0xc0, 0xe2, 0x1a, 0x00, 0x87, 0x97,
	0xd5, 0x4a, 0x66, 0xc9, 0x70, 0x76, 0x24, 0xf7, 0x52, 0x9c, 0xc1, 0x41, 0x8f, 0xde, 0xbf, 0x59,
	0x27, 0xeb, 0x16, 0x7d, 0x9b, 0x2d, 0xd8, 0xb1, 0x9a, 0xe0, 0x1d, 0xfa, 0x56, 0x9c, 0xc2, 0xaa,
	0x71, 0x84, 0x81, 0x64, 0x2d, 0x31, 0x50, 0xb6, 0xdc, 0x44, 0xc5, 0x6c, 0xfb, 0x7f, 0x64, 0xb7,
	0x18, 0x28, 0x7f, 0x80, 0xa4, 0x7a, 0xa5, 0x3f, 0xbe, 0xff, 0xbd, 0x7f, 0xfc, 0xb3, 0xff, 0x34,
	0x9d, 0xd9, 0xd7, 0x74, 0xae, 0x8b, 0xe7, 0xf3, 0xd0, 0x52, 0x20, 0xe7, 0xd4, 0x4e, 0x53, 0xd3,
	0x2a, 0x2d, 0xcb, 0x1b, 0x6d, 0xf7, 0xb2, 0xea, 0xfb, 0xb2, 0xb1, 0xc6, 0xd8, 0x6e, 0xc8, 0x60,
	0xb7, 0xe0, 0x10, 0xae, 0x3e, 0x02, 0x00, 0x00, 0xff, 0xff, 0x98, 0x3f, 0x8f, 0x6b, 0x99, 0x01,
	0x00, 0x00,
}
