// Code generated by protoc-gen-go. DO NOT EDIT.
// source: commontype.proto

package common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetMessage struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMessage) Reset()         { *m = GetMessage{} }
func (m *GetMessage) String() string { return proto.CompactTextString(m) }
func (*GetMessage) ProtoMessage()    {}
func (*GetMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_5465023ec2044510, []int{0}
}

func (m *GetMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMessage.Unmarshal(m, b)
}
func (m *GetMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMessage.Marshal(b, m, deterministic)
}
func (m *GetMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMessage.Merge(m, src)
}
func (m *GetMessage) XXX_Size() int {
	return xxx_messageInfo_GetMessage.Size(m)
}
func (m *GetMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GetMessage proto.InternalMessageInfo

func (m *GetMessage) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ListMessage struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Start                int32    `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	Size                 int32    `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListMessage) Reset()         { *m = ListMessage{} }
func (m *ListMessage) String() string { return proto.CompactTextString(m) }
func (*ListMessage) ProtoMessage()    {}
func (*ListMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_5465023ec2044510, []int{1}
}

func (m *ListMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMessage.Unmarshal(m, b)
}
func (m *ListMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMessage.Marshal(b, m, deterministic)
}
func (m *ListMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMessage.Merge(m, src)
}
func (m *ListMessage) XXX_Size() int {
	return xxx_messageInfo_ListMessage.Size(m)
}
func (m *ListMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ListMessage proto.InternalMessageInfo

func (m *ListMessage) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ListMessage) GetStart() int32 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *ListMessage) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type String struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *String) Reset()         { *m = String{} }
func (m *String) String() string { return proto.CompactTextString(m) }
func (*String) ProtoMessage()    {}
func (*String) Descriptor() ([]byte, []int) {
	return fileDescriptor_5465023ec2044510, []int{2}
}

func (m *String) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_String.Unmarshal(m, b)
}
func (m *String) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_String.Marshal(b, m, deterministic)
}
func (m *String) XXX_Merge(src proto.Message) {
	xxx_messageInfo_String.Merge(m, src)
}
func (m *String) XXX_Size() int {
	return xxx_messageInfo_String.Size(m)
}
func (m *String) XXX_DiscardUnknown() {
	xxx_messageInfo_String.DiscardUnknown(m)
}

var xxx_messageInfo_String proto.InternalMessageInfo

func (m *String) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_5465023ec2044510, []int{3}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GetMessage)(nil), "commontype.GetMessage")
	proto.RegisterType((*ListMessage)(nil), "commontype.ListMessage")
	proto.RegisterType((*String)(nil), "commontype.String")
	proto.RegisterType((*Empty)(nil), "commontype.Empty")
}

func init() { proto.RegisterFile("commontype.proto", fileDescriptor_5465023ec2044510) }

var fileDescriptor_5465023ec2044510 = []byte{
	// 184 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x48, 0xce, 0xcf, 0xcd,
	0xcd, 0xcf, 0x2b, 0xa9, 0x2c, 0x48, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x42, 0x88,
	0x28, 0xc9, 0x70, 0x71, 0xb9, 0xa7, 0x96, 0xf8, 0xa6, 0x16, 0x17, 0x27, 0xa6, 0xa7, 0x0a, 0xf1,
	0x71, 0x31, 0x65, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x31, 0x65, 0xa6, 0x28, 0xb9,
	0x73, 0x71, 0xfb, 0x64, 0x16, 0xe3, 0x92, 0x16, 0x12, 0xe1, 0x62, 0x2d, 0x2e, 0x49, 0x2c, 0x2a,
	0x91, 0x60, 0x52, 0x60, 0xd4, 0x60, 0x0d, 0x82, 0x70, 0x84, 0x84, 0xb8, 0x58, 0x8a, 0x33, 0xab,
	0x52, 0x25, 0x98, 0xc1, 0x82, 0x60, 0xb6, 0x92, 0x1c, 0x17, 0x5b, 0x70, 0x49, 0x51, 0x66, 0x5e,
	0x3a, 0x48, 0x4f, 0x59, 0x62, 0x4e, 0x69, 0x2a, 0xd4, 0x18, 0x08, 0x47, 0x89, 0x9d, 0x8b, 0xd5,
	0x35, 0xb7, 0xa0, 0xa4, 0xd2, 0x49, 0x29, 0x4a, 0xa1, 0x24, 0x23, 0xb5, 0x24, 0xb5, 0xa8, 0x28,
	0x33, 0x29, 0x27, 0x35, 0x39, 0x23, 0x33, 0x27, 0x45, 0xdf, 0x39, 0x27, 0xbf, 0x34, 0xc5, 0xb1,
	0xa0, 0x40, 0x1f, 0xe2, 0xee, 0x24, 0x36, 0xb0, 0x37, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x5a, 0xb8, 0x59, 0xb3, 0xda, 0x00, 0x00, 0x00,
}
