// Code generated by protoc-gen-go. DO NOT EDIT.
// source: connectorservice.proto

package connectorservice

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NovelDownloadRequest struct {
	SourceId             string   `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	NovelId              string   `protobuf:"bytes,2,opt,name=novel_id,json=novelId,proto3" json:"novel_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NovelDownloadRequest) Reset()         { *m = NovelDownloadRequest{} }
func (m *NovelDownloadRequest) String() string { return proto.CompactTextString(m) }
func (*NovelDownloadRequest) ProtoMessage()    {}
func (*NovelDownloadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_connectorservice_384fe828347c19ab, []int{0}
}
func (m *NovelDownloadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NovelDownloadRequest.Unmarshal(m, b)
}
func (m *NovelDownloadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NovelDownloadRequest.Marshal(b, m, deterministic)
}
func (dst *NovelDownloadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NovelDownloadRequest.Merge(dst, src)
}
func (m *NovelDownloadRequest) XXX_Size() int {
	return xxx_messageInfo_NovelDownloadRequest.Size(m)
}
func (m *NovelDownloadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NovelDownloadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NovelDownloadRequest proto.InternalMessageInfo

func (m *NovelDownloadRequest) GetSourceId() string {
	if m != nil {
		return m.SourceId
	}
	return ""
}

func (m *NovelDownloadRequest) GetNovelId() string {
	if m != nil {
		return m.NovelId
	}
	return ""
}

type NovelDownloadReply struct {
	NovelData            *NovelSourceData `protobuf:"bytes,1,opt,name=novel_data,json=novelData,proto3" json:"novel_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *NovelDownloadReply) Reset()         { *m = NovelDownloadReply{} }
func (m *NovelDownloadReply) String() string { return proto.CompactTextString(m) }
func (*NovelDownloadReply) ProtoMessage()    {}
func (*NovelDownloadReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_connectorservice_384fe828347c19ab, []int{1}
}
func (m *NovelDownloadReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NovelDownloadReply.Unmarshal(m, b)
}
func (m *NovelDownloadReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NovelDownloadReply.Marshal(b, m, deterministic)
}
func (dst *NovelDownloadReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NovelDownloadReply.Merge(dst, src)
}
func (m *NovelDownloadReply) XXX_Size() int {
	return xxx_messageInfo_NovelDownloadReply.Size(m)
}
func (m *NovelDownloadReply) XXX_DiscardUnknown() {
	xxx_messageInfo_NovelDownloadReply.DiscardUnknown(m)
}

var xxx_messageInfo_NovelDownloadReply proto.InternalMessageInfo

func (m *NovelDownloadReply) GetNovelData() *NovelSourceData {
	if m != nil {
		return m.NovelData
	}
	return nil
}

type ChapterDownloadRequest struct {
	ChapterMetadata      *ChapterSourceMetadata `protobuf:"bytes,1,opt,name=chapter_metadata,json=chapterMetadata,proto3" json:"chapter_metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ChapterDownloadRequest) Reset()         { *m = ChapterDownloadRequest{} }
func (m *ChapterDownloadRequest) String() string { return proto.CompactTextString(m) }
func (*ChapterDownloadRequest) ProtoMessage()    {}
func (*ChapterDownloadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_connectorservice_384fe828347c19ab, []int{2}
}
func (m *ChapterDownloadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChapterDownloadRequest.Unmarshal(m, b)
}
func (m *ChapterDownloadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChapterDownloadRequest.Marshal(b, m, deterministic)
}
func (dst *ChapterDownloadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChapterDownloadRequest.Merge(dst, src)
}
func (m *ChapterDownloadRequest) XXX_Size() int {
	return xxx_messageInfo_ChapterDownloadRequest.Size(m)
}
func (m *ChapterDownloadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChapterDownloadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChapterDownloadRequest proto.InternalMessageInfo

func (m *ChapterDownloadRequest) GetChapterMetadata() *ChapterSourceMetadata {
	if m != nil {
		return m.ChapterMetadata
	}
	return nil
}

type ChapterDownloadReply struct {
	ChapterData          *ChapterSourceData `protobuf:"bytes,1,opt,name=chapter_data,json=chapterData,proto3" json:"chapter_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ChapterDownloadReply) Reset()         { *m = ChapterDownloadReply{} }
func (m *ChapterDownloadReply) String() string { return proto.CompactTextString(m) }
func (*ChapterDownloadReply) ProtoMessage()    {}
func (*ChapterDownloadReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_connectorservice_384fe828347c19ab, []int{3}
}
func (m *ChapterDownloadReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChapterDownloadReply.Unmarshal(m, b)
}
func (m *ChapterDownloadReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChapterDownloadReply.Marshal(b, m, deterministic)
}
func (dst *ChapterDownloadReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChapterDownloadReply.Merge(dst, src)
}
func (m *ChapterDownloadReply) XXX_Size() int {
	return xxx_messageInfo_ChapterDownloadReply.Size(m)
}
func (m *ChapterDownloadReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ChapterDownloadReply.DiscardUnknown(m)
}

var xxx_messageInfo_ChapterDownloadReply proto.InternalMessageInfo

func (m *ChapterDownloadReply) GetChapterData() *ChapterSourceData {
	if m != nil {
		return m.ChapterData
	}
	return nil
}

type NovelSourceData struct {
	Metadata             *NovelSourceMetadata     `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Chapters             []*ChapterSourceMetadata `protobuf:"bytes,2,rep,name=chapters,proto3" json:"chapters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *NovelSourceData) Reset()         { *m = NovelSourceData{} }
func (m *NovelSourceData) String() string { return proto.CompactTextString(m) }
func (*NovelSourceData) ProtoMessage()    {}
func (*NovelSourceData) Descriptor() ([]byte, []int) {
	return fileDescriptor_connectorservice_384fe828347c19ab, []int{4}
}
func (m *NovelSourceData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NovelSourceData.Unmarshal(m, b)
}
func (m *NovelSourceData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NovelSourceData.Marshal(b, m, deterministic)
}
func (dst *NovelSourceData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NovelSourceData.Merge(dst, src)
}
func (m *NovelSourceData) XXX_Size() int {
	return xxx_messageInfo_NovelSourceData.Size(m)
}
func (m *NovelSourceData) XXX_DiscardUnknown() {
	xxx_messageInfo_NovelSourceData.DiscardUnknown(m)
}

var xxx_messageInfo_NovelSourceData proto.InternalMessageInfo

func (m *NovelSourceData) GetMetadata() *NovelSourceMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *NovelSourceData) GetChapters() []*ChapterSourceMetadata {
	if m != nil {
		return m.Chapters
	}
	return nil
}

type NovelSourceMetadata struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SourceId             string   `protobuf:"bytes,3,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NovelSourceMetadata) Reset()         { *m = NovelSourceMetadata{} }
func (m *NovelSourceMetadata) String() string { return proto.CompactTextString(m) }
func (*NovelSourceMetadata) ProtoMessage()    {}
func (*NovelSourceMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_connectorservice_384fe828347c19ab, []int{5}
}
func (m *NovelSourceMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NovelSourceMetadata.Unmarshal(m, b)
}
func (m *NovelSourceMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NovelSourceMetadata.Marshal(b, m, deterministic)
}
func (dst *NovelSourceMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NovelSourceMetadata.Merge(dst, src)
}
func (m *NovelSourceMetadata) XXX_Size() int {
	return xxx_messageInfo_NovelSourceMetadata.Size(m)
}
func (m *NovelSourceMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_NovelSourceMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_NovelSourceMetadata proto.InternalMessageInfo

func (m *NovelSourceMetadata) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *NovelSourceMetadata) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NovelSourceMetadata) GetSourceId() string {
	if m != nil {
		return m.SourceId
	}
	return ""
}

type ChapterSourceData struct {
	Metadata             *ChapterSourceMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Content              string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ChapterSourceData) Reset()         { *m = ChapterSourceData{} }
func (m *ChapterSourceData) String() string { return proto.CompactTextString(m) }
func (*ChapterSourceData) ProtoMessage()    {}
func (*ChapterSourceData) Descriptor() ([]byte, []int) {
	return fileDescriptor_connectorservice_384fe828347c19ab, []int{6}
}
func (m *ChapterSourceData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChapterSourceData.Unmarshal(m, b)
}
func (m *ChapterSourceData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChapterSourceData.Marshal(b, m, deterministic)
}
func (dst *ChapterSourceData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChapterSourceData.Merge(dst, src)
}
func (m *ChapterSourceData) XXX_Size() int {
	return xxx_messageInfo_ChapterSourceData.Size(m)
}
func (m *ChapterSourceData) XXX_DiscardUnknown() {
	xxx_messageInfo_ChapterSourceData.DiscardUnknown(m)
}

var xxx_messageInfo_ChapterSourceData proto.InternalMessageInfo

func (m *ChapterSourceData) GetMetadata() *ChapterSourceMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *ChapterSourceData) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type ChapterSourceMetadata struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Index                int32    `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	SourceId             string   `protobuf:"bytes,4,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	Url                  string   `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChapterSourceMetadata) Reset()         { *m = ChapterSourceMetadata{} }
func (m *ChapterSourceMetadata) String() string { return proto.CompactTextString(m) }
func (*ChapterSourceMetadata) ProtoMessage()    {}
func (*ChapterSourceMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_connectorservice_384fe828347c19ab, []int{7}
}
func (m *ChapterSourceMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChapterSourceMetadata.Unmarshal(m, b)
}
func (m *ChapterSourceMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChapterSourceMetadata.Marshal(b, m, deterministic)
}
func (dst *ChapterSourceMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChapterSourceMetadata.Merge(dst, src)
}
func (m *ChapterSourceMetadata) XXX_Size() int {
	return xxx_messageInfo_ChapterSourceMetadata.Size(m)
}
func (m *ChapterSourceMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_ChapterSourceMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_ChapterSourceMetadata proto.InternalMessageInfo

func (m *ChapterSourceMetadata) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ChapterSourceMetadata) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ChapterSourceMetadata) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *ChapterSourceMetadata) GetSourceId() string {
	if m != nil {
		return m.SourceId
	}
	return ""
}

func (m *ChapterSourceMetadata) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func init() {
	proto.RegisterType((*NovelDownloadRequest)(nil), "connectorservice.NovelDownloadRequest")
	proto.RegisterType((*NovelDownloadReply)(nil), "connectorservice.NovelDownloadReply")
	proto.RegisterType((*ChapterDownloadRequest)(nil), "connectorservice.ChapterDownloadRequest")
	proto.RegisterType((*ChapterDownloadReply)(nil), "connectorservice.ChapterDownloadReply")
	proto.RegisterType((*NovelSourceData)(nil), "connectorservice.NovelSourceData")
	proto.RegisterType((*NovelSourceMetadata)(nil), "connectorservice.NovelSourceMetadata")
	proto.RegisterType((*ChapterSourceData)(nil), "connectorservice.ChapterSourceData")
	proto.RegisterType((*ChapterSourceMetadata)(nil), "connectorservice.ChapterSourceMetadata")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ConnectorClient is the client API for Connector service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ConnectorClient interface {
	GetNovelData(ctx context.Context, in *NovelDownloadRequest, opts ...grpc.CallOption) (*NovelDownloadReply, error)
	GetChapterData(ctx context.Context, in *ChapterDownloadRequest, opts ...grpc.CallOption) (*ChapterDownloadReply, error)
}

type connectorClient struct {
	cc *grpc.ClientConn
}

func NewConnectorClient(cc *grpc.ClientConn) ConnectorClient {
	return &connectorClient{cc}
}

func (c *connectorClient) GetNovelData(ctx context.Context, in *NovelDownloadRequest, opts ...grpc.CallOption) (*NovelDownloadReply, error) {
	out := new(NovelDownloadReply)
	err := c.cc.Invoke(ctx, "/connectorservice.Connector/GetNovelData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectorClient) GetChapterData(ctx context.Context, in *ChapterDownloadRequest, opts ...grpc.CallOption) (*ChapterDownloadReply, error) {
	out := new(ChapterDownloadReply)
	err := c.cc.Invoke(ctx, "/connectorservice.Connector/GetChapterData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConnectorServer is the server API for Connector service.
type ConnectorServer interface {
	GetNovelData(context.Context, *NovelDownloadRequest) (*NovelDownloadReply, error)
	GetChapterData(context.Context, *ChapterDownloadRequest) (*ChapterDownloadReply, error)
}

func RegisterConnectorServer(s *grpc.Server, srv ConnectorServer) {
	s.RegisterService(&_Connector_serviceDesc, srv)
}

func _Connector_GetNovelData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NovelDownloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectorServer).GetNovelData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/connectorservice.Connector/GetNovelData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectorServer).GetNovelData(ctx, req.(*NovelDownloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Connector_GetChapterData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChapterDownloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectorServer).GetChapterData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/connectorservice.Connector/GetChapterData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectorServer).GetChapterData(ctx, req.(*ChapterDownloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Connector_serviceDesc = grpc.ServiceDesc{
	ServiceName: "connectorservice.Connector",
	HandlerType: (*ConnectorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNovelData",
			Handler:    _Connector_GetNovelData_Handler,
		},
		{
			MethodName: "GetChapterData",
			Handler:    _Connector_GetChapterData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "connectorservice.proto",
}

func init() {
	proto.RegisterFile("connectorservice.proto", fileDescriptor_connectorservice_384fe828347c19ab)
}

var fileDescriptor_connectorservice_384fe828347c19ab = []byte{
	// 414 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xcf, 0xf2, 0xd2, 0x30,
	0x10, 0xb6, 0x05, 0xa4, 0x5d, 0x18, 0xc0, 0x88, 0x4c, 0xd5, 0x0b, 0x46, 0x45, 0x4e, 0x1c, 0xf0,
	0x05, 0x74, 0xca, 0xc8, 0x70, 0x90, 0x43, 0x9d, 0xe1, 0x08, 0x13, 0x9b, 0xcc, 0xd8, 0x99, 0x92,
	0xd4, 0x36, 0xa0, 0xdc, 0x7c, 0x0d, 0x1f, 0xcb, 0x37, 0x72, 0x9a, 0xfe, 0x01, 0x52, 0x10, 0xfc,
	0xdd, 0x92, 0xcd, 0x7e, 0xfb, 0xed, 0xb7, 0xfb, 0xb5, 0x30, 0xf0, 0x05, 0xe7, 0xcc, 0x97, 0x22,
	0x4e, 0x58, 0xbc, 0x0f, 0x7c, 0x36, 0x89, 0x62, 0x21, 0x05, 0xea, 0xe9, 0x71, 0xbc, 0x84, 0xfe,
	0x52, 0xec, 0x59, 0x38, 0x13, 0x3f, 0x78, 0x28, 0x08, 0xf5, 0xd8, 0xf7, 0x1d, 0x4b, 0x24, 0x7a,
	0x09, 0x76, 0x22, 0x76, 0xb1, 0xcf, 0x36, 0x01, 0x75, 0x8c, 0xa1, 0x31, 0xb6, 0x3d, 0x2b, 0x0b,
	0x2c, 0x28, 0x7a, 0x0e, 0x16, 0x4f, 0x41, 0xe9, 0x9b, 0xa9, 0xde, 0x9a, 0xea, 0xbe, 0xa0, 0x78,
	0x05, 0x48, 0xab, 0x17, 0x85, 0x07, 0xf4, 0x01, 0x20, 0x03, 0x50, 0x22, 0x89, 0x2a, 0xd7, 0x9a,
	0xbe, 0x9a, 0x54, 0x9a, 0x54, 0xc8, 0x2f, 0x8a, 0x65, 0x46, 0x24, 0xf1, 0x6c, 0x05, 0x4a, 0x8f,
	0x38, 0x84, 0x81, 0xfb, 0x8d, 0x44, 0x92, 0xc5, 0x7a, 0xa7, 0x1e, 0xf4, 0xfc, 0xec, 0x65, 0xb3,
	0x65, 0x92, 0x9c, 0x30, 0xbc, 0xab, 0x32, 0xe4, 0x35, 0x32, 0x8e, 0xcf, 0x79, 0xba, 0xd7, 0xcd,
	0x0b, 0x14, 0x01, 0xbc, 0x86, 0x7e, 0x85, 0x2d, 0xd5, 0xf1, 0x09, 0xda, 0x05, 0xd7, 0x09, 0xcf,
	0xeb, 0x1b, 0x3c, 0x4a, 0x4b, 0x2b, 0x07, 0x2a, 0x35, 0xbf, 0x0d, 0xe8, 0x6a, 0x62, 0xd1, 0x47,
	0xb0, 0xb4, 0xfe, 0xdf, 0xfe, 0x73, 0x42, 0x65, 0xf7, 0x25, 0x0c, 0xb9, 0x60, 0xe5, 0x2c, 0x89,
	0x63, 0x0e, 0x6b, 0xff, 0x33, 0x82, 0x12, 0x88, 0x57, 0xf0, 0xf4, 0x02, 0x0b, 0xea, 0x80, 0x59,
	0x3a, 0xc1, 0x0c, 0x28, 0x42, 0x50, 0xe7, 0x64, 0xcb, 0xf2, 0xfd, 0xab, 0xf3, 0xb9, 0x69, 0x6a,
	0xe7, 0xa6, 0xc1, 0x31, 0x3c, 0xa9, 0x4c, 0x25, 0xed, 0xf8, 0xa1, 0x4b, 0x3b, 0xca, 0x76, 0xa0,
	0xe9, 0x0b, 0x2e, 0x19, 0x97, 0x85, 0x1b, 0xf3, 0x2b, 0xfe, 0x65, 0xc0, 0xb3, 0x8b, 0xe8, 0xbb,
	0xe4, 0xf4, 0xa1, 0x11, 0x70, 0xca, 0x7e, 0x2a, 0x29, 0x0d, 0x2f, 0xbb, 0x9c, 0x8b, 0xac, 0x6b,
	0x5f, 0x46, 0x0f, 0x6a, 0xbb, 0x38, 0x74, 0x1a, 0x2a, 0x9c, 0x1e, 0xa7, 0x7f, 0x0c, 0xb0, 0xdd,
	0x42, 0x11, 0x5a, 0x43, 0x7b, 0xce, 0xe4, 0xb2, 0xb0, 0x35, 0x1a, 0x5d, 0x59, 0xb1, 0x66, 0xf2,
	0x17, 0x6f, 0x6e, 0xe6, 0x45, 0xe1, 0x01, 0x3f, 0x42, 0x14, 0x3a, 0x73, 0x26, 0xdd, 0xa3, 0xd5,
	0xd0, 0xf8, 0xea, 0x3c, 0x75, 0x8e, 0xd1, 0x1d, 0x99, 0x8a, 0xe5, 0xeb, 0x63, 0xf5, 0x37, 0x79,
	0xff, 0x37, 0x00, 0x00, 0xff, 0xff, 0xda, 0x74, 0x6e, 0x83, 0x67, 0x04, 0x00, 0x00,
}
