// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/adminservice.proto

package model

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
	common "theterriblechild/CloudApp/common"
	model "theterriblechild/CloudApp/common/model"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateAccountMessage struct {
	Name                 string             `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CreateUser           *CreateUserMessage `protobuf:"bytes,2,opt,name=create_user,json=createUser,proto3" json:"create_user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *CreateAccountMessage) Reset()         { *m = CreateAccountMessage{} }
func (m *CreateAccountMessage) String() string { return proto.CompactTextString(m) }
func (*CreateAccountMessage) ProtoMessage()    {}
func (*CreateAccountMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_96292a55e4fedcbc, []int{0}
}

func (m *CreateAccountMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountMessage.Unmarshal(m, b)
}
func (m *CreateAccountMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountMessage.Marshal(b, m, deterministic)
}
func (m *CreateAccountMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountMessage.Merge(m, src)
}
func (m *CreateAccountMessage) XXX_Size() int {
	return xxx_messageInfo_CreateAccountMessage.Size(m)
}
func (m *CreateAccountMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountMessage.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountMessage proto.InternalMessageInfo

func (m *CreateAccountMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateAccountMessage) GetCreateUser() *CreateUserMessage {
	if m != nil {
		return m.CreateUser
	}
	return nil
}

type CreateUserMessage struct {
	UserCreationToken    string   `protobuf:"bytes,1,opt,name=user_creation_token,json=userCreationToken,proto3" json:"user_creation_token,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserMessage) Reset()         { *m = CreateUserMessage{} }
func (m *CreateUserMessage) String() string { return proto.CompactTextString(m) }
func (*CreateUserMessage) ProtoMessage()    {}
func (*CreateUserMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_96292a55e4fedcbc, []int{1}
}

func (m *CreateUserMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserMessage.Unmarshal(m, b)
}
func (m *CreateUserMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserMessage.Marshal(b, m, deterministic)
}
func (m *CreateUserMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserMessage.Merge(m, src)
}
func (m *CreateUserMessage) XXX_Size() int {
	return xxx_messageInfo_CreateUserMessage.Size(m)
}
func (m *CreateUserMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserMessage.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserMessage proto.InternalMessageInfo

func (m *CreateUserMessage) GetUserCreationToken() string {
	if m != nil {
		return m.UserCreationToken
	}
	return ""
}

func (m *CreateUserMessage) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type SetPasswordMessage struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OldPassword          string   `protobuf:"bytes,2,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	NewPassword          string   `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetPasswordMessage) Reset()         { *m = SetPasswordMessage{} }
func (m *SetPasswordMessage) String() string { return proto.CompactTextString(m) }
func (*SetPasswordMessage) ProtoMessage()    {}
func (*SetPasswordMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_96292a55e4fedcbc, []int{2}
}

func (m *SetPasswordMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetPasswordMessage.Unmarshal(m, b)
}
func (m *SetPasswordMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetPasswordMessage.Marshal(b, m, deterministic)
}
func (m *SetPasswordMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetPasswordMessage.Merge(m, src)
}
func (m *SetPasswordMessage) XXX_Size() int {
	return xxx_messageInfo_SetPasswordMessage.Size(m)
}
func (m *SetPasswordMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SetPasswordMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SetPasswordMessage proto.InternalMessageInfo

func (m *SetPasswordMessage) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SetPasswordMessage) GetOldPassword() string {
	if m != nil {
		return m.OldPassword
	}
	return ""
}

func (m *SetPasswordMessage) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

type SetPasswordWithTokenMessage struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NewPassword          string   `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetPasswordWithTokenMessage) Reset()         { *m = SetPasswordWithTokenMessage{} }
func (m *SetPasswordWithTokenMessage) String() string { return proto.CompactTextString(m) }
func (*SetPasswordWithTokenMessage) ProtoMessage()    {}
func (*SetPasswordWithTokenMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_96292a55e4fedcbc, []int{3}
}

func (m *SetPasswordWithTokenMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetPasswordWithTokenMessage.Unmarshal(m, b)
}
func (m *SetPasswordWithTokenMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetPasswordWithTokenMessage.Marshal(b, m, deterministic)
}
func (m *SetPasswordWithTokenMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetPasswordWithTokenMessage.Merge(m, src)
}
func (m *SetPasswordWithTokenMessage) XXX_Size() int {
	return xxx_messageInfo_SetPasswordWithTokenMessage.Size(m)
}
func (m *SetPasswordWithTokenMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SetPasswordWithTokenMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SetPasswordWithTokenMessage proto.InternalMessageInfo

func (m *SetPasswordWithTokenMessage) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SetPasswordWithTokenMessage) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

type ResetPasswordMessage struct {
	UserEmail            string   `protobuf:"bytes,1,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetPasswordMessage) Reset()         { *m = ResetPasswordMessage{} }
func (m *ResetPasswordMessage) String() string { return proto.CompactTextString(m) }
func (*ResetPasswordMessage) ProtoMessage()    {}
func (*ResetPasswordMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_96292a55e4fedcbc, []int{4}
}

func (m *ResetPasswordMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetPasswordMessage.Unmarshal(m, b)
}
func (m *ResetPasswordMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetPasswordMessage.Marshal(b, m, deterministic)
}
func (m *ResetPasswordMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetPasswordMessage.Merge(m, src)
}
func (m *ResetPasswordMessage) XXX_Size() int {
	return xxx_messageInfo_ResetPasswordMessage.Size(m)
}
func (m *ResetPasswordMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetPasswordMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ResetPasswordMessage proto.InternalMessageInfo

func (m *ResetPasswordMessage) GetUserEmail() string {
	if m != nil {
		return m.UserEmail
	}
	return ""
}

type CreateAgentMessage struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AgentName            string   `protobuf:"bytes,2,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAgentMessage) Reset()         { *m = CreateAgentMessage{} }
func (m *CreateAgentMessage) String() string { return proto.CompactTextString(m) }
func (*CreateAgentMessage) ProtoMessage()    {}
func (*CreateAgentMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_96292a55e4fedcbc, []int{5}
}

func (m *CreateAgentMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAgentMessage.Unmarshal(m, b)
}
func (m *CreateAgentMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAgentMessage.Marshal(b, m, deterministic)
}
func (m *CreateAgentMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAgentMessage.Merge(m, src)
}
func (m *CreateAgentMessage) XXX_Size() int {
	return xxx_messageInfo_CreateAgentMessage.Size(m)
}
func (m *CreateAgentMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAgentMessage.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAgentMessage proto.InternalMessageInfo

func (m *CreateAgentMessage) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *CreateAgentMessage) GetAgentName() string {
	if m != nil {
		return m.AgentName
	}
	return ""
}

type RegisterUserRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterUserRequest) Reset()         { *m = RegisterUserRequest{} }
func (m *RegisterUserRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterUserRequest) ProtoMessage()    {}
func (*RegisterUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_96292a55e4fedcbc, []int{6}
}

func (m *RegisterUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterUserRequest.Unmarshal(m, b)
}
func (m *RegisterUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterUserRequest.Marshal(b, m, deterministic)
}
func (m *RegisterUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterUserRequest.Merge(m, src)
}
func (m *RegisterUserRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterUserRequest.Size(m)
}
func (m *RegisterUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterUserRequest proto.InternalMessageInfo

func (m *RegisterUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type RegisterUserResponse struct {
	VerificationToken    string   `protobuf:"bytes,1,opt,name=verification_token,json=verificationToken,proto3" json:"verification_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterUserResponse) Reset()         { *m = RegisterUserResponse{} }
func (m *RegisterUserResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterUserResponse) ProtoMessage()    {}
func (*RegisterUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_96292a55e4fedcbc, []int{7}
}

func (m *RegisterUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterUserResponse.Unmarshal(m, b)
}
func (m *RegisterUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterUserResponse.Marshal(b, m, deterministic)
}
func (m *RegisterUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterUserResponse.Merge(m, src)
}
func (m *RegisterUserResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterUserResponse.Size(m)
}
func (m *RegisterUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterUserResponse proto.InternalMessageInfo

func (m *RegisterUserResponse) GetVerificationToken() string {
	if m != nil {
		return m.VerificationToken
	}
	return ""
}

type ConfirmCodeRequest struct {
	VerificationToken    string   `protobuf:"bytes,1,opt,name=verification_token,json=verificationToken,proto3" json:"verification_token,omitempty"`
	VerificationCode     string   `protobuf:"bytes,2,opt,name=verification_code,json=verificationCode,proto3" json:"verification_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmCodeRequest) Reset()         { *m = ConfirmCodeRequest{} }
func (m *ConfirmCodeRequest) String() string { return proto.CompactTextString(m) }
func (*ConfirmCodeRequest) ProtoMessage()    {}
func (*ConfirmCodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_96292a55e4fedcbc, []int{8}
}

func (m *ConfirmCodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmCodeRequest.Unmarshal(m, b)
}
func (m *ConfirmCodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmCodeRequest.Marshal(b, m, deterministic)
}
func (m *ConfirmCodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmCodeRequest.Merge(m, src)
}
func (m *ConfirmCodeRequest) XXX_Size() int {
	return xxx_messageInfo_ConfirmCodeRequest.Size(m)
}
func (m *ConfirmCodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmCodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmCodeRequest proto.InternalMessageInfo

func (m *ConfirmCodeRequest) GetVerificationToken() string {
	if m != nil {
		return m.VerificationToken
	}
	return ""
}

func (m *ConfirmCodeRequest) GetVerificationCode() string {
	if m != nil {
		return m.VerificationCode
	}
	return ""
}

type ConfirmCodeResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	UserCreationToken    string   `protobuf:"bytes,2,opt,name=user_creation_token,json=userCreationToken,proto3" json:"user_creation_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmCodeResponse) Reset()         { *m = ConfirmCodeResponse{} }
func (m *ConfirmCodeResponse) String() string { return proto.CompactTextString(m) }
func (*ConfirmCodeResponse) ProtoMessage()    {}
func (*ConfirmCodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_96292a55e4fedcbc, []int{9}
}

func (m *ConfirmCodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmCodeResponse.Unmarshal(m, b)
}
func (m *ConfirmCodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmCodeResponse.Marshal(b, m, deterministic)
}
func (m *ConfirmCodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmCodeResponse.Merge(m, src)
}
func (m *ConfirmCodeResponse) XXX_Size() int {
	return xxx_messageInfo_ConfirmCodeResponse.Size(m)
}
func (m *ConfirmCodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmCodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmCodeResponse proto.InternalMessageInfo

func (m *ConfirmCodeResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ConfirmCodeResponse) GetUserCreationToken() string {
	if m != nil {
		return m.UserCreationToken
	}
	return ""
}

type LoginRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_96292a55e4fedcbc, []int{10}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *LoginRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type LoginResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_96292a55e4fedcbc, []int{11}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CreateAccountMessage)(nil), "adminservice.CreateAccountMessage")
	proto.RegisterType((*CreateUserMessage)(nil), "adminservice.CreateUserMessage")
	proto.RegisterType((*SetPasswordMessage)(nil), "adminservice.SetPasswordMessage")
	proto.RegisterType((*SetPasswordWithTokenMessage)(nil), "adminservice.SetPasswordWithTokenMessage")
	proto.RegisterType((*ResetPasswordMessage)(nil), "adminservice.ResetPasswordMessage")
	proto.RegisterType((*CreateAgentMessage)(nil), "adminservice.CreateAgentMessage")
	proto.RegisterType((*RegisterUserRequest)(nil), "adminservice.RegisterUserRequest")
	proto.RegisterType((*RegisterUserResponse)(nil), "adminservice.RegisterUserResponse")
	proto.RegisterType((*ConfirmCodeRequest)(nil), "adminservice.ConfirmCodeRequest")
	proto.RegisterType((*ConfirmCodeResponse)(nil), "adminservice.ConfirmCodeResponse")
	proto.RegisterType((*LoginRequest)(nil), "adminservice.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "adminservice.LoginResponse")
}

func init() { proto.RegisterFile("proto/adminservice.proto", fileDescriptor_96292a55e4fedcbc) }

var fileDescriptor_96292a55e4fedcbc = []byte{
	// 871 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0xdd, 0x6e, 0xdc, 0x44,
	0x14, 0xd6, 0x9a, 0x96, 0x36, 0xc7, 0x9b, 0xb4, 0x99, 0x2c, 0xed, 0xd6, 0xcd, 0x42, 0x32, 0x20,
	0x14, 0x1a, 0xb1, 0x56, 0x83, 0x2a, 0xa4, 0x5e, 0x11, 0x56, 0x51, 0x85, 0x54, 0x50, 0xe5, 0xf2,
	0x23, 0x01, 0x92, 0xe5, 0xda, 0xa7, 0xbb, 0x03, 0xb6, 0xc7, 0x78, 0xc6, 0x09, 0xab, 0xaa, 0x37,
	0x48, 0xdc, 0x70, 0x0b, 0x6f, 0xc6, 0x2b, 0xf0, 0x20, 0x68, 0x7e, 0x9c, 0xb5, 0xd7, 0xce, 0x56,
	0xbd, 0x59, 0xed, 0x9c, 0x73, 0xe6, 0x7c, 0xdf, 0x9c, 0x9f, 0x4f, 0x86, 0x71, 0x51, 0x72, 0xc9,
	0xfd, 0x28, 0xc9, 0x58, 0x2e, 0xb0, 0x3c, 0x67, 0x31, 0x4e, 0xb5, 0x89, 0x0c, 0x9b, 0x36, 0x6f,
	0x7f, 0xce, 0xf9, 0x3c, 0x45, 0x3f, 0x2a, 0x98, 0x1f, 0xe5, 0x39, 0x97, 0x91, 0x64, 0x3c, 0x17,
	0x26, 0xd6, 0xbb, 0x1d, 0xf3, 0x2c, 0xe3, 0xb9, 0x5c, 0x16, 0xf6, 0xb6, 0xb7, 0x9b, 0xf1, 0x04,
	0x53, 0x5f, 0xff, 0x1a, 0x13, 0x4d, 0x61, 0x34, 0x2b, 0x31, 0x92, 0x78, 0x1a, 0xc7, 0xbc, 0xca,
	0xe5, 0xd7, 0x28, 0x44, 0x34, 0x47, 0x42, 0xe0, 0x5a, 0x1e, 0x65, 0x38, 0x1e, 0x1c, 0x0c, 0x8e,
	0xb6, 0x02, 0xfd, 0x9f, 0x7c, 0x01, 0x6e, 0xac, 0x63, 0xc3, 0x4a, 0x60, 0x39, 0x76, 0x0e, 0x06,
	0x47, 0xee, 0xc9, 0x07, 0xd3, 0x16, 0x4d, 0x93, 0xec, 0x3b, 0x81, 0xa5, 0xcd, 0x14, 0x40, 0x7c,
	0x69, 0xa2, 0x21, 0xec, 0x76, 0x02, 0xc8, 0x14, 0xf6, 0x54, 0xbe, 0x50, 0xc7, 0x31, 0x9e, 0x87,
	0x92, 0xff, 0x8a, 0xb9, 0x45, 0xde, 0x55, 0xae, 0x99, 0xf5, 0x7c, 0xab, 0x1c, 0xc4, 0x83, 0x9b,
	0x45, 0x24, 0xc4, 0x05, 0x2f, 0x13, 0xcd, 0x61, 0x2b, 0xb8, 0x3c, 0xd3, 0x5f, 0x80, 0x3c, 0x47,
	0xf9, 0xcc, 0x1e, 0x6b, 0x84, 0x1d, 0x70, 0x58, 0x62, 0x13, 0x3a, 0x2c, 0x21, 0x87, 0x30, 0xe4,
	0x69, 0x12, 0xae, 0x65, 0x71, 0x79, 0x9a, 0xd4, 0x37, 0x55, 0x48, 0x8e, 0x17, 0xab, 0x90, 0x77,
	0x4c, 0x48, 0x8e, 0x17, 0x75, 0x08, 0x7d, 0x06, 0xf7, 0x1b, 0x58, 0x3f, 0x30, 0xb9, 0xd0, 0xfc,
	0x36, 0x80, 0xb6, 0x32, 0x3a, 0xdd, 0x8c, 0x8f, 0x60, 0x14, 0xa0, 0xe8, 0xf2, 0x9f, 0x00, 0xe8,
	0x0a, 0x61, 0x16, 0xb1, 0xd4, 0xa6, 0xdc, 0x52, 0x96, 0x33, 0x65, 0xa0, 0x01, 0x10, 0xdb, 0xc3,
	0x39, 0xae, 0x3a, 0x38, 0x01, 0x88, 0x4c, 0x4f, 0xc3, 0x4b, 0x1e, 0x5b, 0xd6, 0xf2, 0x55, 0xa2,
	0xdd, 0x2a, 0x3c, 0xd4, 0x6d, 0x76, 0xac, 0x5b, 0x59, 0xbe, 0x89, 0x32, 0xa4, 0xc7, 0xb0, 0x17,
	0xe0, 0x9c, 0x09, 0x89, 0xa5, 0xea, 0x55, 0x80, 0xbf, 0x55, 0x28, 0x24, 0x19, 0xc1, 0xf5, 0x26,
	0x09, 0x73, 0xa0, 0x67, 0x8a, 0x77, 0x33, 0x58, 0x14, 0x3c, 0x17, 0x48, 0x3e, 0x05, 0x72, 0x8e,
	0x25, 0x7b, 0xc9, 0xe2, 0x9e, 0xc6, 0x36, 0x3d, 0xba, 0x70, 0xb4, 0x00, 0x32, 0xe3, 0xf9, 0x4b,
	0x56, 0x66, 0x33, 0x9e, 0x60, 0x0d, 0xf9, 0x76, 0x49, 0xc8, 0x31, 0xb4, 0x8c, 0x61, 0xcc, 0x93,
	0xfa, 0x79, 0xb7, 0x9b, 0x0e, 0x05, 0x41, 0x43, 0xd8, 0x6b, 0x21, 0x5a, 0xde, 0x63, 0xb8, 0x21,
	0xaa, 0x38, 0x46, 0x21, 0x34, 0xce, 0xcd, 0xa0, 0x3e, 0x5e, 0x35, 0xab, 0xce, 0x15, 0xb3, 0x4a,
	0xbf, 0x87, 0xe1, 0x53, 0x3e, 0x67, 0xf9, 0xc6, 0xfa, 0x6d, 0x9a, 0x68, 0x75, 0xc3, 0x60, 0x98,
	0x09, 0x34, 0x07, 0x7a, 0x0b, 0xb6, 0x6d, 0x5e, 0x43, 0xf9, 0xe4, 0x02, 0x76, 0xec, 0x06, 0x3f,
	0x37, 0x9b, 0x48, 0x10, 0xb6, 0x5b, 0x9b, 0x4d, 0x68, 0xdf, 0xa6, 0xb6, 0xd7, 0xde, 0xdb, 0x9d,
	0x36, 0x44, 0xe3, 0x2c, 0x2b, 0xe4, 0x92, 0x4e, 0xfe, 0xf8, 0xf7, 0xbf, 0xbf, 0x9d, 0xbb, 0x94,
	0x18, 0x3d, 0xf2, 0xcf, 0x1f, 0xfa, 0x76, 0x8a, 0xc4, 0xe3, 0xc1, 0x83, 0x93, 0x7f, 0xae, 0x81,
	0xab, 0x9a, 0x5e, 0xc3, 0xfe, 0x0c, 0xb0, 0x5a, 0x71, 0xf2, 0x26, 0x75, 0xe8, 0x03, 0xf4, 0x34,
	0xe0, 0x88, 0xde, 0x5a, 0x01, 0xaa, 0xc2, 0x2a, 0x34, 0xf2, 0x14, 0x6e, 0x3c, 0x41, 0xa9, 0x53,
	0xdf, 0x69, 0xde, 0x7c, 0x82, 0x97, 0x4f, 0x70, 0xa7, 0x46, 0xdf, 0xb4, 0xe0, 0xec, 0xeb, 0x5c,
	0x77, 0xc8, 0x68, 0x2d, 0x97, 0xff, 0x8a, 0x25, 0xaf, 0x49, 0x0a, 0x6e, 0x63, 0x83, 0xc9, 0x41,
	0x9b, 0x6c, 0x57, 0x48, 0xfa, 0xd8, 0x1e, 0x69, 0x04, 0x4a, 0x27, 0x7d, 0x08, 0x7e, 0xdd, 0x46,
	0xc5, 0x7d, 0x09, 0xa3, 0x3e, 0xbd, 0x20, 0x9f, 0x5c, 0x09, 0xbb, 0xae, 0x29, 0x7d, 0xf8, 0x1f,
	0x6a, 0xfc, 0x09, 0x1d, 0xaf, 0xe3, 0x37, 0xa1, 0x0b, 0xd8, 0x6e, 0x09, 0xcb, 0xfa, 0x2c, 0xf4,
	0xa9, 0xce, 0x5b, 0x3d, 0xb6, 0x54, 0x09, 0x1a, 0x88, 0x27, 0x7f, 0x0e, 0x60, 0xa8, 0xe5, 0xa8,
	0x9e, 0x8b, 0x0a, 0xdc, 0x86, 0x48, 0xad, 0xd7, 0xba, 0xab, 0x5f, 0x7d, 0xf0, 0x0f, 0x35, 0xfc,
	0x31, 0xfd, 0xb8, 0x3b, 0x8a, 0xfe, 0xab, 0x95, 0xd8, 0xbd, 0xf6, 0xb5, 0x8e, 0xe9, 0xf1, 0xfc,
	0xcb, 0xa9, 0x85, 0xac, 0xd4, 0x6b, 0x59, 0xd3, 0x59, 0xc2, 0xb0, 0x29, 0x59, 0xe4, 0x70, 0xbd,
	0x20, 0x1d, 0xed, 0xf3, 0xe8, 0xa6, 0x10, 0xb3, 0x86, 0x94, 0x6a, 0x86, 0xfb, 0xf4, 0xee, 0x8a,
	0x61, 0x69, 0xe3, 0x74, 0xa5, 0x54, 0x33, 0x7e, 0x07, 0xb7, 0x21, 0x3a, 0x9d, 0x4a, 0x74, 0x14,
	0xd0, 0x3b, 0xdc, 0x10, 0x61, 0x71, 0x3f, 0xd2, 0xb8, 0xef, 0xd3, 0x7b, 0x3d, 0xb8, 0x5a, 0xf5,
	0x96, 0xaa, 0x18, 0x12, 0xde, 0x3b, 0xad, 0xe4, 0x02, 0x73, 0x69, 0x45, 0xb0, 0xae, 0xc6, 0x4f,
	0x70, 0x5d, 0xcb, 0x09, 0xf1, 0xda, 0x50, 0x4d, 0xed, 0xf2, 0xee, 0xf7, 0xfa, 0x2c, 0x81, 0x7b,
	0x9a, 0xc0, 0x1e, 0xdd, 0xf1, 0xa3, 0x4a, 0x2e, 0x14, 0x7e, 0xaa, 0xfc, 0x8f, 0x07, 0x0f, 0xbe,
	0xfc, 0xfc, 0xc7, 0x47, 0x72, 0x81, 0x12, 0xcb, 0x92, 0xbd, 0x48, 0x31, 0x5e, 0xb0, 0x34, 0xf1,
	0x67, 0x29, 0xaf, 0x92, 0xd3, 0xa2, 0xf0, 0xa3, 0xa2, 0x48, 0x2d, 0x19, 0x61, 0xb8, 0x47, 0x45,
	0x61, 0xbe, 0x50, 0x5e, 0xbc, 0xab, 0x3f, 0x51, 0x3e, 0xfb, 0x3f, 0x00, 0x00, 0xff, 0xff, 0xa5,
	0xec, 0xc7, 0x34, 0x0f, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountServiceClient is the client API for AccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountServiceClient interface {
	CreateAccount(ctx context.Context, in *CreateAccountMessage, opts ...grpc.CallOption) (*common.Empty, error)
}

type accountServiceClient struct {
	cc *grpc.ClientConn
}

func NewAccountServiceClient(cc *grpc.ClientConn) AccountServiceClient {
	return &accountServiceClient{cc}
}

func (c *accountServiceClient) CreateAccount(ctx context.Context, in *CreateAccountMessage, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/adminservice.AccountService/CreateAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServiceServer is the server API for AccountService service.
type AccountServiceServer interface {
	CreateAccount(context.Context, *CreateAccountMessage) (*common.Empty, error)
}

func RegisterAccountServiceServer(s *grpc.Server, srv AccountServiceServer) {
	s.RegisterService(&_AccountService_serviceDesc, srv)
}

func _AccountService_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/adminservice.AccountService/CreateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).CreateAccount(ctx, req.(*CreateAccountMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccountService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "adminservice.AccountService",
	HandlerType: (*AccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAccount",
			Handler:    _AccountService_CreateAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/adminservice.proto",
}

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	CreateUser(ctx context.Context, in *CreateUserMessage, opts ...grpc.CallOption) (*common.Empty, error)
	GetUser(ctx context.Context, in *common.GetMessage, opts ...grpc.CallOption) (*model.User, error)
	SetPassword(ctx context.Context, in *SetPasswordMessage, opts ...grpc.CallOption) (*common.Empty, error)
	SetPasswordWithToken(ctx context.Context, in *SetPasswordWithTokenMessage, opts ...grpc.CallOption) (*common.Empty, error)
	ResetPassword(ctx context.Context, in *ResetPasswordMessage, opts ...grpc.CallOption) (*common.Empty, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) CreateUser(ctx context.Context, in *CreateUserMessage, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/adminservice.UserService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUser(ctx context.Context, in *common.GetMessage, opts ...grpc.CallOption) (*model.User, error) {
	out := new(model.User)
	err := c.cc.Invoke(ctx, "/adminservice.UserService/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) SetPassword(ctx context.Context, in *SetPasswordMessage, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/adminservice.UserService/SetPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) SetPasswordWithToken(ctx context.Context, in *SetPasswordWithTokenMessage, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/adminservice.UserService/SetPasswordWithToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ResetPassword(ctx context.Context, in *ResetPasswordMessage, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/adminservice.UserService/ResetPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	CreateUser(context.Context, *CreateUserMessage) (*common.Empty, error)
	GetUser(context.Context, *common.GetMessage) (*model.User, error)
	SetPassword(context.Context, *SetPasswordMessage) (*common.Empty, error)
	SetPasswordWithToken(context.Context, *SetPasswordWithTokenMessage) (*common.Empty, error)
	ResetPassword(context.Context, *ResetPasswordMessage) (*common.Empty, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/adminservice.UserService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateUser(ctx, req.(*CreateUserMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.GetMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/adminservice.UserService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUser(ctx, req.(*common.GetMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_SetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPasswordMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).SetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/adminservice.UserService/SetPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).SetPassword(ctx, req.(*SetPasswordMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_SetPasswordWithToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPasswordWithTokenMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).SetPasswordWithToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/adminservice.UserService/SetPasswordWithToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).SetPasswordWithToken(ctx, req.(*SetPasswordWithTokenMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ResetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetPasswordMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ResetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/adminservice.UserService/ResetPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ResetPassword(ctx, req.(*ResetPasswordMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "adminservice.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _UserService_CreateUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _UserService_GetUser_Handler,
		},
		{
			MethodName: "SetPassword",
			Handler:    _UserService_SetPassword_Handler,
		},
		{
			MethodName: "SetPasswordWithToken",
			Handler:    _UserService_SetPasswordWithToken_Handler,
		},
		{
			MethodName: "ResetPassword",
			Handler:    _UserService_ResetPassword_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/adminservice.proto",
}

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AgentServiceClient interface {
	CreateAgent(ctx context.Context, in *CreateAgentMessage, opts ...grpc.CallOption) (*common.Empty, error)
}

type agentServiceClient struct {
	cc *grpc.ClientConn
}

func NewAgentServiceClient(cc *grpc.ClientConn) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) CreateAgent(ctx context.Context, in *CreateAgentMessage, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/adminservice.AgentService/CreateAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
type AgentServiceServer interface {
	CreateAgent(context.Context, *CreateAgentMessage) (*common.Empty, error)
}

func RegisterAgentServiceServer(s *grpc.Server, srv AgentServiceServer) {
	s.RegisterService(&_AgentService_serviceDesc, srv)
}

func _AgentService_CreateAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAgentMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).CreateAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/adminservice.AgentService/CreateAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).CreateAgent(ctx, req.(*CreateAgentMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _AgentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "adminservice.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAgent",
			Handler:    _AgentService_CreateAgent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/adminservice.proto",
}

// RegistrationServiceClient is the client API for RegistrationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RegistrationServiceClient interface {
	RegisterUser(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*RegisterUserResponse, error)
	ConfirmCode(ctx context.Context, in *ConfirmCodeRequest, opts ...grpc.CallOption) (*ConfirmCodeResponse, error)
}

type registrationServiceClient struct {
	cc *grpc.ClientConn
}

func NewRegistrationServiceClient(cc *grpc.ClientConn) RegistrationServiceClient {
	return &registrationServiceClient{cc}
}

func (c *registrationServiceClient) RegisterUser(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*RegisterUserResponse, error) {
	out := new(RegisterUserResponse)
	err := c.cc.Invoke(ctx, "/adminservice.RegistrationService/RegisterUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registrationServiceClient) ConfirmCode(ctx context.Context, in *ConfirmCodeRequest, opts ...grpc.CallOption) (*ConfirmCodeResponse, error) {
	out := new(ConfirmCodeResponse)
	err := c.cc.Invoke(ctx, "/adminservice.RegistrationService/ConfirmCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegistrationServiceServer is the server API for RegistrationService service.
type RegistrationServiceServer interface {
	RegisterUser(context.Context, *RegisterUserRequest) (*RegisterUserResponse, error)
	ConfirmCode(context.Context, *ConfirmCodeRequest) (*ConfirmCodeResponse, error)
}

func RegisterRegistrationServiceServer(s *grpc.Server, srv RegistrationServiceServer) {
	s.RegisterService(&_RegistrationService_serviceDesc, srv)
}

func _RegistrationService_RegisterUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistrationServiceServer).RegisterUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/adminservice.RegistrationService/RegisterUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistrationServiceServer).RegisterUser(ctx, req.(*RegisterUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistrationService_ConfirmCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistrationServiceServer).ConfirmCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/adminservice.RegistrationService/ConfirmCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistrationServiceServer).ConfirmCode(ctx, req.(*ConfirmCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RegistrationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "adminservice.RegistrationService",
	HandlerType: (*RegistrationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterUser",
			Handler:    _RegistrationService_RegisterUser_Handler,
		},
		{
			MethodName: "ConfirmCode",
			Handler:    _RegistrationService_ConfirmCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/adminservice.proto",
}

// AuthenticationServiceClient is the client API for AuthenticationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthenticationServiceClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
}

type authenticationServiceClient struct {
	cc *grpc.ClientConn
}

func NewAuthenticationServiceClient(cc *grpc.ClientConn) AuthenticationServiceClient {
	return &authenticationServiceClient{cc}
}

func (c *authenticationServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/adminservice.AuthenticationService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthenticationServiceServer is the server API for AuthenticationService service.
type AuthenticationServiceServer interface {
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
}

func RegisterAuthenticationServiceServer(s *grpc.Server, srv AuthenticationServiceServer) {
	s.RegisterService(&_AuthenticationService_serviceDesc, srv)
}

func _AuthenticationService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/adminservice.AuthenticationService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthenticationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "adminservice.AuthenticationService",
	HandlerType: (*AuthenticationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _AuthenticationService_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/adminservice.proto",
}
