// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/adminservice.proto

package model

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateAccountMessage struct {
	Name                 string             `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CreateUser           *CreateUserMessage `protobuf:"bytes,2,opt,name=create_user,json=createUser,proto3" json:"create_user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *CreateAccountMessage) Reset()         { *m = CreateAccountMessage{} }
func (m *CreateAccountMessage) String() string { return proto.CompactTextString(m) }
func (*CreateAccountMessage) ProtoMessage()    {}
func (*CreateAccountMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_96292a55e4fedcbc, []int{0}
}

func (m *CreateAccountMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountMessage.Unmarshal(m, b)
}
func (m *CreateAccountMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountMessage.Marshal(b, m, deterministic)
}
func (m *CreateAccountMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountMessage.Merge(m, src)
}
func (m *CreateAccountMessage) XXX_Size() int {
	return xxx_messageInfo_CreateAccountMessage.Size(m)
}
func (m *CreateAccountMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountMessage.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountMessage proto.InternalMessageInfo

func (m *CreateAccountMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateAccountMessage) GetCreateUser() *CreateUserMessage {
	if m != nil {
		return m.CreateUser
	}
	return nil
}

type CreateUserMessage struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	AccountId            string   `protobuf:"bytes,5,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserMessage) Reset()         { *m = CreateUserMessage{} }
func (m *CreateUserMessage) String() string { return proto.CompactTextString(m) }
func (*CreateUserMessage) ProtoMessage()    {}
func (*CreateUserMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_96292a55e4fedcbc, []int{1}
}

func (m *CreateUserMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserMessage.Unmarshal(m, b)
}
func (m *CreateUserMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserMessage.Marshal(b, m, deterministic)
}
func (m *CreateUserMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserMessage.Merge(m, src)
}
func (m *CreateUserMessage) XXX_Size() int {
	return xxx_messageInfo_CreateUserMessage.Size(m)
}
func (m *CreateUserMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserMessage.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserMessage proto.InternalMessageInfo

func (m *CreateUserMessage) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUserMessage) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *CreateUserMessage) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *CreateUserMessage) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateUserMessage) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

type GetMessage struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Paging               *Paging  `protobuf:"bytes,2,opt,name=paging,proto3" json:"paging,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMessage) Reset()         { *m = GetMessage{} }
func (m *GetMessage) String() string { return proto.CompactTextString(m) }
func (*GetMessage) ProtoMessage()    {}
func (*GetMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_96292a55e4fedcbc, []int{2}
}

func (m *GetMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMessage.Unmarshal(m, b)
}
func (m *GetMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMessage.Marshal(b, m, deterministic)
}
func (m *GetMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMessage.Merge(m, src)
}
func (m *GetMessage) XXX_Size() int {
	return xxx_messageInfo_GetMessage.Size(m)
}
func (m *GetMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GetMessage proto.InternalMessageInfo

func (m *GetMessage) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetMessage) GetPaging() *Paging {
	if m != nil {
		return m.Paging
	}
	return nil
}

type Paging struct {
	Start                int32    `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	Size                 int32    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Paging) Reset()         { *m = Paging{} }
func (m *Paging) String() string { return proto.CompactTextString(m) }
func (*Paging) ProtoMessage()    {}
func (*Paging) Descriptor() ([]byte, []int) {
	return fileDescriptor_96292a55e4fedcbc, []int{3}
}

func (m *Paging) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Paging.Unmarshal(m, b)
}
func (m *Paging) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Paging.Marshal(b, m, deterministic)
}
func (m *Paging) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Paging.Merge(m, src)
}
func (m *Paging) XXX_Size() int {
	return xxx_messageInfo_Paging.Size(m)
}
func (m *Paging) XXX_DiscardUnknown() {
	xxx_messageInfo_Paging.DiscardUnknown(m)
}

var xxx_messageInfo_Paging proto.InternalMessageInfo

func (m *Paging) GetStart() int32 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *Paging) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type CreateAgentMessage struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AgentName            string   `protobuf:"bytes,2,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAgentMessage) Reset()         { *m = CreateAgentMessage{} }
func (m *CreateAgentMessage) String() string { return proto.CompactTextString(m) }
func (*CreateAgentMessage) ProtoMessage()    {}
func (*CreateAgentMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_96292a55e4fedcbc, []int{4}
}

func (m *CreateAgentMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAgentMessage.Unmarshal(m, b)
}
func (m *CreateAgentMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAgentMessage.Marshal(b, m, deterministic)
}
func (m *CreateAgentMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAgentMessage.Merge(m, src)
}
func (m *CreateAgentMessage) XXX_Size() int {
	return xxx_messageInfo_CreateAgentMessage.Size(m)
}
func (m *CreateAgentMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAgentMessage.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAgentMessage proto.InternalMessageInfo

func (m *CreateAgentMessage) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *CreateAgentMessage) GetAgentName() string {
	if m != nil {
		return m.AgentName
	}
	return ""
}

type String struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *String) Reset()         { *m = String{} }
func (m *String) String() string { return proto.CompactTextString(m) }
func (*String) ProtoMessage()    {}
func (*String) Descriptor() ([]byte, []int) {
	return fileDescriptor_96292a55e4fedcbc, []int{5}
}

func (m *String) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_String.Unmarshal(m, b)
}
func (m *String) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_String.Marshal(b, m, deterministic)
}
func (m *String) XXX_Merge(src proto.Message) {
	xxx_messageInfo_String.Merge(m, src)
}
func (m *String) XXX_Size() int {
	return xxx_messageInfo_String.Size(m)
}
func (m *String) XXX_DiscardUnknown() {
	xxx_messageInfo_String.DiscardUnknown(m)
}

var xxx_messageInfo_String proto.InternalMessageInfo

func (m *String) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_96292a55e4fedcbc, []int{6}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Account struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_96292a55e4fedcbc, []int{7}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Account) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FirstName            string   `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	AccountId            string   `protobuf:"bytes,5,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Password             string   `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	PasswordSalt         string   `protobuf:"bytes,7,opt,name=password_salt,json=passwordSalt,proto3" json:"password_salt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_96292a55e4fedcbc, []int{8}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetPasswordSalt() string {
	if m != nil {
		return m.PasswordSalt
	}
	return ""
}

type Agent struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId            string   `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Agent) Reset()         { *m = Agent{} }
func (m *Agent) String() string { return proto.CompactTextString(m) }
func (*Agent) ProtoMessage()    {}
func (*Agent) Descriptor() ([]byte, []int) {
	return fileDescriptor_96292a55e4fedcbc, []int{9}
}

func (m *Agent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Agent.Unmarshal(m, b)
}
func (m *Agent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Agent.Marshal(b, m, deterministic)
}
func (m *Agent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Agent.Merge(m, src)
}
func (m *Agent) XXX_Size() int {
	return xxx_messageInfo_Agent.Size(m)
}
func (m *Agent) XXX_DiscardUnknown() {
	xxx_messageInfo_Agent.DiscardUnknown(m)
}

var xxx_messageInfo_Agent proto.InternalMessageInfo

func (m *Agent) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Agent) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *Agent) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateAccountMessage)(nil), "adminservice.CreateAccountMessage")
	proto.RegisterType((*CreateUserMessage)(nil), "adminservice.CreateUserMessage")
	proto.RegisterType((*GetMessage)(nil), "adminservice.GetMessage")
	proto.RegisterType((*Paging)(nil), "adminservice.Paging")
	proto.RegisterType((*CreateAgentMessage)(nil), "adminservice.CreateAgentMessage")
	proto.RegisterType((*String)(nil), "adminservice.String")
	proto.RegisterType((*Empty)(nil), "adminservice.Empty")
	proto.RegisterType((*Account)(nil), "adminservice.Account")
	proto.RegisterType((*User)(nil), "adminservice.User")
	proto.RegisterType((*Agent)(nil), "adminservice.Agent")
}

func init() { proto.RegisterFile("proto/adminservice.proto", fileDescriptor_96292a55e4fedcbc) }

var fileDescriptor_96292a55e4fedcbc = []byte{
	// 608 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x96, 0x9d, 0x38, 0x69, 0x27, 0x2d, 0x82, 0x25, 0x42, 0x56, 0xa0, 0x25, 0xda, 0x5e, 0x42,
	0x05, 0xb5, 0x08, 0x42, 0x48, 0x3d, 0x11, 0x2a, 0x54, 0x51, 0x09, 0x84, 0x1c, 0xb8, 0x70, 0x09,
	0x5b, 0x7b, 0x71, 0x57, 0xda, 0xd8, 0xd6, 0xee, 0x26, 0x08, 0x2a, 0x2e, 0xbc, 0x02, 0x2f, 0xc0,
	0x85, 0x77, 0xe1, 0xce, 0x2b, 0xf0, 0x20, 0x68, 0x77, 0xed, 0x38, 0x4e, 0xd2, 0x72, 0xb1, 0x3c,
	0x3f, 0xfa, 0xbe, 0x99, 0xf9, 0x66, 0x16, 0xfc, 0x5c, 0x64, 0x2a, 0x0b, 0x48, 0x3c, 0x65, 0xa9,
	0xa4, 0x62, 0xce, 0x22, 0x7a, 0x64, 0x5c, 0x68, 0x67, 0xd9, 0xd7, 0xbb, 0x97, 0x64, 0x59, 0xc2,
	0x69, 0x40, 0x72, 0x16, 0x90, 0x34, 0xcd, 0x14, 0x51, 0x2c, 0x4b, 0xa5, 0xcd, 0xc5, 0x1c, 0xba,
	0x27, 0x82, 0x12, 0x45, 0x47, 0x51, 0x94, 0xcd, 0x52, 0xf5, 0x9a, 0x4a, 0x49, 0x12, 0x8a, 0x10,
	0x34, 0x53, 0x32, 0xa5, 0xbe, 0xd3, 0x77, 0x06, 0xdb, 0xa1, 0xf9, 0x47, 0xcf, 0xa1, 0x13, 0x99,
	0xdc, 0xc9, 0x4c, 0x52, 0xe1, 0xbb, 0x7d, 0x67, 0xd0, 0x19, 0xde, 0x3f, 0xaa, 0x55, 0x60, 0xc1,
	0xde, 0x4b, 0x2a, 0x0a, 0xa4, 0x10, 0xa2, 0x85, 0x0b, 0xff, 0x74, 0xe0, 0xd6, 0x5a, 0x06, 0xea,
	0x82, 0x47, 0xa7, 0x84, 0xf1, 0x82, 0xcc, 0x1a, 0x68, 0x0f, 0xe0, 0x13, 0x13, 0x52, 0x4d, 0x4c,
	0x1d, 0xae, 0x09, 0x6d, 0x1b, 0xcf, 0x1b, 0x5d, 0xcc, 0x5d, 0xd8, 0xe6, 0xa4, 0x8c, 0x36, 0x4c,
	0x74, 0x4b, 0x3b, 0x4c, 0xb0, 0x07, 0x5b, 0x39, 0x91, 0xf2, 0x73, 0x26, 0x62, 0xbf, 0x69, 0x63,
	0xa5, 0xad, 0x71, 0x89, 0xed, 0x75, 0xc2, 0x62, 0xdf, 0xb3, 0xb8, 0x85, 0xe7, 0x55, 0x8c, 0xcf,
	0x00, 0x4e, 0xe9, 0x62, 0x0c, 0x37, 0xc0, 0x65, 0x71, 0x51, 0x97, 0xcb, 0x62, 0xf4, 0x10, 0x5a,
	0x39, 0x49, 0x58, 0x9a, 0x14, 0xdd, 0x77, 0xeb, 0xdd, 0xbf, 0x35, 0xb1, 0xb0, 0xc8, 0xc1, 0x43,
	0x68, 0x59, 0x8f, 0x6e, 0x51, 0x2a, 0x22, 0x94, 0x81, 0xf2, 0x42, 0x6b, 0xe8, 0x21, 0x4b, 0xf6,
	0xd5, 0x36, 0xe7, 0x85, 0xe6, 0x1f, 0x87, 0x80, 0x0a, 0x41, 0x12, 0x5a, 0xc9, 0x51, 0x2f, 0xda,
	0x59, 0x29, 0xda, 0x84, 0x75, 0x7a, 0x6d, 0x56, 0xc6, 0xa3, 0xc7, 0x81, 0xf7, 0xa1, 0x35, 0x56,
	0xa2, 0xa8, 0x63, 0x4e, 0xf8, 0xac, 0xd4, 0xd5, 0x1a, 0xb8, 0x0d, 0xde, 0xcb, 0x69, 0xae, 0xbe,
	0xe0, 0x47, 0xd0, 0x2e, 0xf6, 0x60, 0xad, 0xf3, 0x72, 0x21, 0xdc, 0x6a, 0x21, 0xf0, 0x6f, 0x07,
	0x9a, 0x5a, 0xc8, 0xb5, 0xe4, 0x85, 0xa2, 0xee, 0xd5, 0x8a, 0x36, 0xae, 0x55, 0xb4, 0xb9, 0xa2,
	0xe8, 0xf5, 0xaa, 0xd5, 0x04, 0x6f, 0xad, 0x08, 0x7e, 0x00, 0xbb, 0xe5, 0xff, 0x44, 0x12, 0xae,
	0xfc, 0xb6, 0x49, 0xd8, 0x29, 0x9d, 0x63, 0xc2, 0x15, 0x3e, 0x03, 0xcf, 0x0c, 0x7c, 0xad, 0x95,
	0x3a, 0xb1, 0xbb, 0x4a, 0x5c, 0x8e, 0xa5, 0x51, 0x8d, 0x65, 0xf8, 0xab, 0x01, 0x3b, 0x23, 0xbd,
	0x16, 0x63, 0xbb, 0x16, 0xe8, 0x23, 0xec, 0xd6, 0x8e, 0x0c, 0xe1, 0x4d, 0x47, 0x53, 0xbf, 0xc0,
	0xde, 0xed, 0x7a, 0x8e, 0x15, 0xe8, 0xce, 0xf7, 0x3f, 0x7f, 0x7f, 0xb8, 0x37, 0x71, 0x27, 0x98,
	0x3f, 0x0e, 0x8a, 0x2a, 0x8e, 0x9d, 0x43, 0xc4, 0x01, 0xaa, 0xbb, 0x42, 0xff, 0xbb, 0xc9, 0xcd,
	0xd8, 0x03, 0x83, 0x8d, 0xf1, 0xde, 0x12, 0x76, 0x70, 0x59, 0x35, 0xff, 0x2d, 0xd0, 0x67, 0xaf,
	0xd9, 0xde, 0x41, 0xfb, 0x94, 0x2a, 0x43, 0xe5, 0xd7, 0x91, 0xaa, 0xd3, 0xd9, 0xcc, 0xd1, 0x33,
	0x1c, 0x5d, 0x84, 0x34, 0x87, 0x86, 0x0b, 0x2e, 0xf5, 0x57, 0xa3, 0xa3, 0x0c, 0x3a, 0x4b, 0x9b,
	0x8f, 0xfa, 0x1b, 0x67, 0xb4, 0x74, 0x14, 0x9b, 0x19, 0x1e, 0x18, 0x86, 0x03, 0xbc, 0x7f, 0x65,
	0x17, 0xe6, 0x2e, 0x8e, 0x9d, 0xc3, 0x17, 0xcf, 0x3e, 0x3c, 0x55, 0x17, 0x54, 0x51, 0x21, 0xd8,
	0x39, 0xa7, 0xd1, 0x05, 0xe3, 0x71, 0x70, 0xc2, 0xb3, 0x59, 0x3c, 0xca, 0xf3, 0x80, 0xe4, 0x39,
	0x67, 0x91, 0x7d, 0x2b, 0xed, 0x23, 0x4b, 0xf2, 0x3c, 0x98, 0x66, 0x31, 0xe5, 0xe7, 0x2d, 0xf3,
	0x76, 0x3e, 0xf9, 0x17, 0x00, 0x00, 0xff, 0xff, 0x79, 0xa8, 0x21, 0xbc, 0x83, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AdminServiceClient interface {
	CreateAccount(ctx context.Context, in *CreateAccountMessage, opts ...grpc.CallOption) (*Empty, error)
	CreateUser(ctx context.Context, in *CreateUserMessage, opts ...grpc.CallOption) (*Empty, error)
	GetUser(ctx context.Context, in *GetMessage, opts ...grpc.CallOption) (*Empty, error)
	CreateAgent(ctx context.Context, in *CreateAgentMessage, opts ...grpc.CallOption) (*Empty, error)
}

type adminServiceClient struct {
	cc *grpc.ClientConn
}

func NewAdminServiceClient(cc *grpc.ClientConn) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) CreateAccount(ctx context.Context, in *CreateAccountMessage, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/adminservice.AdminService/CreateAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) CreateUser(ctx context.Context, in *CreateUserMessage, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/adminservice.AdminService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetUser(ctx context.Context, in *GetMessage, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/adminservice.AdminService/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) CreateAgent(ctx context.Context, in *CreateAgentMessage, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/adminservice.AdminService/CreateAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServiceServer is the server API for AdminService service.
type AdminServiceServer interface {
	CreateAccount(context.Context, *CreateAccountMessage) (*Empty, error)
	CreateUser(context.Context, *CreateUserMessage) (*Empty, error)
	GetUser(context.Context, *GetMessage) (*Empty, error)
	CreateAgent(context.Context, *CreateAgentMessage) (*Empty, error)
}

func RegisterAdminServiceServer(s *grpc.Server, srv AdminServiceServer) {
	s.RegisterService(&_AdminService_serviceDesc, srv)
}

func _AdminService_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/adminservice.AdminService/CreateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).CreateAccount(ctx, req.(*CreateAccountMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/adminservice.AdminService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).CreateUser(ctx, req.(*CreateUserMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/adminservice.AdminService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetUser(ctx, req.(*GetMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_CreateAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAgentMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).CreateAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/adminservice.AdminService/CreateAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).CreateAgent(ctx, req.(*CreateAgentMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _AdminService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "adminservice.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAccount",
			Handler:    _AdminService_CreateAccount_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _AdminService_CreateUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _AdminService_GetUser_Handler,
		},
		{
			MethodName: "CreateAgent",
			Handler:    _AdminService_CreateAgent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/adminservice.proto",
}
